# the name of the plugin
PLUGIN_NAME = icron

# the dissector sources (without any helpers)
DISSECTOR_SRC = \
	packet-icron.c

# Dissector helpers. They're included in the source files in this
# directory, but they're not dissectors themselves, i.e. they're not
# used to generate "plugin.c".
DISSECTOR_SUPPORT_SRC =
