/*Icron Technologies ***** Copyright 2015 All Rights Reserved. ******/
/**/
/**** This file is auto generated by IDesignSpec (http://www.agnisys.com) . Please do not edit this file. ****/
/* created by        : Remco van Steeden*/
/* generated by      : Remco.vanSteeden*/
/* generated from    : Y:\designs\blackbird\working\remcos\blackbird_rc\m_dp_source\regs\ids\tico_decoder\tico_decoder_regs.docx*/
/* IDesignSpec rev   : 6.8.10.0*/

/**** This code is generated with following settings ****/
/* Reg Width                  : 32*/
/* Address Unit               : 8*/
/* C++ Types int              : uint%d_t*/
/* Bus Type                   : AXI*/
/* BigEndian                  : true*/
/* LittleEndian               : true*/
/* Dist. Decode and Readback  : false*/
/*--------------------------------------------------------------------------------------------------------------- */

/*block : tico_decoder */

#ifndef _TICO_DECODER_REGS_H_
#define _TICO_DECODER_REGS_H_

#ifndef __ASSEMBLER__
#ifndef __ASSEMBLER__
typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv2 : 30;
            uint32_t tico_d_config : 2;           /* 1:0 SW=rw HW=ro 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t tico_d_config : 2;           /* 0:1 SW=rw HW=ro 0x0 */
            uint32_t resv2 : 30;
        } bf;
        
    #endif
    uint32_t  dw;
} tico_decoder_tico_d_config;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv16 : 16;
            uint32_t tico_d_width : 16;           /* 15:0 SW=ro HW=ro 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t tico_d_width : 16;           /* 0:15 SW=ro HW=ro 0x0 */
            uint32_t resv16 : 16;
        } bf;
        
    #endif
    uint32_t  dw;
} tico_decoder_tico_d_width;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv16 : 16;
            uint32_t tico_d_height : 16;           /* 15:0 SW=ro HW=ro 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t tico_d_height : 16;           /* 0:15 SW=ro HW=ro 0x0 */
            uint32_t resv16 : 16;
        } bf;
        
    #endif
    uint32_t  dw;
} tico_decoder_tico_d_height;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv2 : 30;
            uint32_t tico_d_comp : 2;           /* 1:0 SW=ro HW=ro 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t tico_d_comp : 2;           /* 0:1 SW=ro HW=ro 0x0 */
            uint32_t resv2 : 30;
        } bf;
        
    #endif
    uint32_t  dw;
} tico_decoder_tico_d_comp;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv2 : 30;
            uint32_t tico_d_mode : 2;           /* 1:0 SW=rw HW=ro 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t tico_d_mode : 2;           /* 0:1 SW=rw HW=ro 0x0 */
            uint32_t resv2 : 30;
        } bf;
        
    #endif
    uint32_t  dw;
} tico_decoder_tico_d_mode;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv3 : 29;
            uint32_t tico_d_hlvls : 3;           /* 2:0 SW=ro HW=ro 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t tico_d_hlvls : 3;           /* 0:2 SW=ro HW=ro 0x0 */
            uint32_t resv3 : 29;
        } bf;
        
    #endif
    uint32_t  dw;
} tico_decoder_tico_d_hlvls;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv1 : 31;
            uint32_t tico_d_vld : 1;           /* 0 SW=wo HW=ro 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t tico_d_vld : 1;           /* 0 SW=wo HW=ro 0x0 */
            uint32_t resv1 : 31;
        } bf;
        
    #endif
    uint32_t  dw;
} tico_decoder_tico_d_vld;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv16 : 16;
            uint32_t tico_d_nbr : 16;           /* 15:0 SW=rw HW=ro 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t tico_d_nbr : 16;           /* 0:15 SW=rw HW=ro 0x0 */
            uint32_t resv16 : 16;
        } bf;
        
    #endif
    uint32_t  dw;
} tico_decoder_tico_d_nbr;

typedef union {
    struct {
        uint32_t tico_d_bgt : 32;           /* 31:0 SW=ro HW=ro 0x0 */
    } bf;
    uint32_t  dw;
} tico_decoder_tico_d_bgt;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv4 : 28;
            uint32_t tico_d_vid_depth : 4;           /* 3:0 SW=ro HW=ro 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t tico_d_vid_depth : 4;           /* 0:3 SW=ro HW=ro 0x0 */
            uint32_t resv4 : 28;
        } bf;
        
    #endif
    uint32_t  dw;
} tico_decoder_tico_d_vid_depth;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv1 : 31;
            uint32_t tico_d_play_mode : 1;           /* 0 SW=wo HW=ro 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t tico_d_play_mode : 1;           /* 0 SW=wo HW=ro 0x0 */
            uint32_t resv1 : 31;
        } bf;
        
    #endif
    uint32_t  dw;
} tico_decoder_tico_d_play_mode;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv2 : 30;
            uint32_t tico_d_profile : 2;           /* 1:0 SW=ro HW=ro 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t tico_d_profile : 2;           /* 0:1 SW=ro HW=ro 0x0 */
            uint32_t resv2 : 30;
        } bf;
        
    #endif
    uint32_t  dw;
} tico_decoder_tico_d_profile;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv16 : 16;
            uint32_t tico_d_line_duration : 16;           /* 15:0 SW=rw HW=ro 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t tico_d_line_duration : 16;           /* 0:15 SW=rw HW=ro 0x0 */
            uint32_t resv16 : 16;
        } bf;
        
    #endif
    uint32_t  dw;
} tico_decoder_tico_d_line_duration;

typedef union {
    struct {
        uint32_t tico_d_line_duration : 32;           /* 31:0 SW=rw HW=ro 0x0 */
    } bf;
    uint32_t  dw;
} tico_decoder_tico_d_img_size;

typedef struct {
    
    uint8_t filler1[0x10];
    
    tico_decoder_tico_d_config  tico_d_config;
    tico_decoder_tico_d_width  tico_d_width;
    
    uint8_t filler3[0x4];
    
    tico_decoder_tico_d_height  tico_d_height;
    
    uint8_t filler4[0x4];
    
    tico_decoder_tico_d_comp  tico_d_comp;
    
    uint8_t filler5[0x4];
    
    tico_decoder_tico_d_mode  tico_d_mode;
    
    uint8_t filler6[0x4];
    
    tico_decoder_tico_d_hlvls  tico_d_hlvls;
    tico_decoder_tico_d_vld  tico_d_vld;
    tico_decoder_tico_d_nbr  tico_d_nbr;
    
    uint8_t filler9[0x4];
    
    tico_decoder_tico_d_bgt  tico_d_bgt;
    tico_decoder_tico_d_vid_depth  tico_d_vid_depth;
    tico_decoder_tico_d_play_mode  tico_d_play_mode;
    
    uint8_t filler12[0x8];
    
    tico_decoder_tico_d_profile  tico_d_profile;
    
    uint8_t filler13[0x24];
    
    tico_decoder_tico_d_line_duration  tico_d_line_duration;
    tico_decoder_tico_d_img_size  tico_d_img_size;
    
    
    uint8_t filler19[0x78];
    
    
} tico_decoder_s;


#endif   //__ASSEMBLER__


#endif // __ASSEMBLER__
#define tico_decoder_tico_d_config_READMASK 0x3
#define tico_decoder_tico_d_config_WRITEMASK 0x3
#define tico_decoder_tico_d_config_VOLATILEMASK 0x0
#define tico_decoder_tico_d_config_RESETMASK 0x3
#define tico_decoder_tico_d_config_DEFAULT 0x00000000

#define tico_decoder_tico_d_width_READMASK 0xFFFF
#define tico_decoder_tico_d_width_WRITEMASK 0x0
#define tico_decoder_tico_d_width_VOLATILEMASK 0x0
#define tico_decoder_tico_d_width_RESETMASK 0xFFFF
#define tico_decoder_tico_d_width_DEFAULT 0x00000000

#define tico_decoder_tico_d_height_READMASK 0xFFFF
#define tico_decoder_tico_d_height_WRITEMASK 0x0
#define tico_decoder_tico_d_height_VOLATILEMASK 0x0
#define tico_decoder_tico_d_height_RESETMASK 0xFFFF
#define tico_decoder_tico_d_height_DEFAULT 0x00000000

#define tico_decoder_tico_d_comp_READMASK 0x3
#define tico_decoder_tico_d_comp_WRITEMASK 0x0
#define tico_decoder_tico_d_comp_VOLATILEMASK 0x0
#define tico_decoder_tico_d_comp_RESETMASK 0x3
#define tico_decoder_tico_d_comp_DEFAULT 0x00000000

#define tico_decoder_tico_d_mode_READMASK 0x3
#define tico_decoder_tico_d_mode_WRITEMASK 0x3
#define tico_decoder_tico_d_mode_VOLATILEMASK 0x0
#define tico_decoder_tico_d_mode_RESETMASK 0x3
#define tico_decoder_tico_d_mode_DEFAULT 0x00000000

#define tico_decoder_tico_d_hlvls_READMASK 0x7
#define tico_decoder_tico_d_hlvls_WRITEMASK 0x0
#define tico_decoder_tico_d_hlvls_VOLATILEMASK 0x0
#define tico_decoder_tico_d_hlvls_RESETMASK 0x7
#define tico_decoder_tico_d_hlvls_DEFAULT 0x00000000

#define tico_decoder_tico_d_vld_READMASK 0x0
#define tico_decoder_tico_d_vld_WRITEMASK 0x1
#define tico_decoder_tico_d_vld_VOLATILEMASK 0x0
#define tico_decoder_tico_d_vld_RESETMASK 0x1
#define tico_decoder_tico_d_vld_DEFAULT 0x00000000

#define tico_decoder_tico_d_nbr_READMASK 0xFFFF
#define tico_decoder_tico_d_nbr_WRITEMASK 0xFFFF
#define tico_decoder_tico_d_nbr_VOLATILEMASK 0x0
#define tico_decoder_tico_d_nbr_RESETMASK 0xFFFF
#define tico_decoder_tico_d_nbr_DEFAULT 0x00000000

#define tico_decoder_tico_d_bgt_READMASK 0xFFFFFFFF
#define tico_decoder_tico_d_bgt_WRITEMASK 0x0
#define tico_decoder_tico_d_bgt_VOLATILEMASK 0x0
#define tico_decoder_tico_d_bgt_RESETMASK 0xFFFFFFFF
#define tico_decoder_tico_d_bgt_DEFAULT 0x00000000

#define tico_decoder_tico_d_vid_depth_READMASK 0xF
#define tico_decoder_tico_d_vid_depth_WRITEMASK 0x0
#define tico_decoder_tico_d_vid_depth_VOLATILEMASK 0x0
#define tico_decoder_tico_d_vid_depth_RESETMASK 0xF
#define tico_decoder_tico_d_vid_depth_DEFAULT 0x00000000

#define tico_decoder_tico_d_play_mode_READMASK 0x0
#define tico_decoder_tico_d_play_mode_WRITEMASK 0x1
#define tico_decoder_tico_d_play_mode_VOLATILEMASK 0x0
#define tico_decoder_tico_d_play_mode_RESETMASK 0x1
#define tico_decoder_tico_d_play_mode_DEFAULT 0x00000000

#define tico_decoder_tico_d_profile_READMASK 0x3
#define tico_decoder_tico_d_profile_WRITEMASK 0x0
#define tico_decoder_tico_d_profile_VOLATILEMASK 0x0
#define tico_decoder_tico_d_profile_RESETMASK 0x3
#define tico_decoder_tico_d_profile_DEFAULT 0x00000000

#define tico_decoder_tico_d_line_duration_READMASK 0xFFFF
#define tico_decoder_tico_d_line_duration_WRITEMASK 0xFFFF
#define tico_decoder_tico_d_line_duration_VOLATILEMASK 0x0
#define tico_decoder_tico_d_line_duration_RESETMASK 0xFFFF
#define tico_decoder_tico_d_line_duration_DEFAULT 0x00000000

#define tico_decoder_tico_d_img_size_READMASK 0xFFFFFFFF
#define tico_decoder_tico_d_img_size_WRITEMASK 0xFFFFFFFF
#define tico_decoder_tico_d_img_size_VOLATILEMASK 0x0
#define tico_decoder_tico_d_img_size_RESETMASK 0xFFFFFFFF
#define tico_decoder_tico_d_img_size_DEFAULT 0x00000000

#define tico_decoder_s_SIZE 0x100
#define tico_decoder_tico_d_config_SIZE 0x4
#define tico_decoder_tico_d_width_SIZE 0x4
#define tico_decoder_tico_d_height_SIZE 0x4
#define tico_decoder_tico_d_comp_SIZE 0x4
#define tico_decoder_tico_d_mode_SIZE 0x4
#define tico_decoder_tico_d_hlvls_SIZE 0x4
#define tico_decoder_tico_d_vld_SIZE 0x4
#define tico_decoder_tico_d_nbr_SIZE 0x4
#define tico_decoder_tico_d_bgt_SIZE 0x4
#define tico_decoder_tico_d_vid_depth_SIZE 0x4
#define tico_decoder_tico_d_play_mode_SIZE 0x4
#define tico_decoder_tico_d_profile_SIZE 0x4
#define tico_decoder_tico_d_line_duration_SIZE 0x4
#define tico_decoder_tico_d_img_size_SIZE 0x4

#define tico_decoder_s_OFFSET 0x0
#define tico_decoder_tico_d_config_OFFSET 0x10
#define tico_decoder_tico_d_width_OFFSET 0x14
#define tico_decoder_tico_d_height_OFFSET 0x1C
#define tico_decoder_tico_d_comp_OFFSET 0x24
#define tico_decoder_tico_d_mode_OFFSET 0x2C
#define tico_decoder_tico_d_hlvls_OFFSET 0x34
#define tico_decoder_tico_d_vld_OFFSET 0x38
#define tico_decoder_tico_d_nbr_OFFSET 0x3C
#define tico_decoder_tico_d_bgt_OFFSET 0x44
#define tico_decoder_tico_d_vid_depth_OFFSET 0x48
#define tico_decoder_tico_d_play_mode_OFFSET 0x4C
#define tico_decoder_tico_d_profile_OFFSET 0x58
#define tico_decoder_tico_d_line_duration_OFFSET 0x80
#define tico_decoder_tico_d_img_size_OFFSET 0x84

#define tico_decoder_s_ADDRESS 0x000
#define tico_decoder_tico_d_config_ADDRESS 0x010
#define tico_decoder_tico_d_width_ADDRESS 0x014
#define tico_decoder_tico_d_height_ADDRESS 0x01C
#define tico_decoder_tico_d_comp_ADDRESS 0x024
#define tico_decoder_tico_d_mode_ADDRESS 0x02C
#define tico_decoder_tico_d_hlvls_ADDRESS 0x034
#define tico_decoder_tico_d_vld_ADDRESS 0x038
#define tico_decoder_tico_d_nbr_ADDRESS 0x03C
#define tico_decoder_tico_d_bgt_ADDRESS 0x044
#define tico_decoder_tico_d_vid_depth_ADDRESS 0x048
#define tico_decoder_tico_d_play_mode_ADDRESS 0x04C
#define tico_decoder_tico_d_profile_ADDRESS 0x058
#define tico_decoder_tico_d_line_duration_ADDRESS 0x080
#define tico_decoder_tico_d_img_size_ADDRESS 0x084
#define TICO_DECODER_TICO_D_CONFIG_TICO_D_CONFIG_OFFSET 0
#define TICO_DECODER_TICO_D_CONFIG_TICO_D_CONFIG_MASK 0x3
#define TICO_DECODER_TICO_D_WIDTH_TICO_D_WIDTH_OFFSET 0
#define TICO_DECODER_TICO_D_WIDTH_TICO_D_WIDTH_MASK 0xFFFF
#define TICO_DECODER_TICO_D_HEIGHT_TICO_D_HEIGHT_OFFSET 0
#define TICO_DECODER_TICO_D_HEIGHT_TICO_D_HEIGHT_MASK 0xFFFF
#define TICO_DECODER_TICO_D_COMP_TICO_D_COMP_OFFSET 0
#define TICO_DECODER_TICO_D_COMP_TICO_D_COMP_MASK 0x3
#define TICO_DECODER_TICO_D_MODE_TICO_D_MODE_OFFSET 0
#define TICO_DECODER_TICO_D_MODE_TICO_D_MODE_MASK 0x3
#define TICO_DECODER_TICO_D_HLVLS_TICO_D_HLVLS_OFFSET 0
#define TICO_DECODER_TICO_D_HLVLS_TICO_D_HLVLS_MASK 0x7
#define TICO_DECODER_TICO_D_VLD_TICO_D_VLD_OFFSET 0
#define TICO_DECODER_TICO_D_VLD_TICO_D_VLD_MASK 0x1
#define TICO_DECODER_TICO_D_VLD_TICO_D_VLD 0x1
#define TICO_DECODER_TICO_D_NBR_TICO_D_NBR_OFFSET 0
#define TICO_DECODER_TICO_D_NBR_TICO_D_NBR_MASK 0xFFFF
#define TICO_DECODER_TICO_D_BGT_TICO_D_BGT_OFFSET 0
#define TICO_DECODER_TICO_D_BGT_TICO_D_BGT_MASK 0xFFFFFFFF
#define TICO_DECODER_TICO_D_VID_DEPTH_TICO_D_VID_DEPTH_OFFSET 0
#define TICO_DECODER_TICO_D_VID_DEPTH_TICO_D_VID_DEPTH_MASK 0xF
#define TICO_DECODER_TICO_D_PLAY_MODE_TICO_D_PLAY_MODE_OFFSET 0
#define TICO_DECODER_TICO_D_PLAY_MODE_TICO_D_PLAY_MODE_MASK 0x1
#define TICO_DECODER_TICO_D_PLAY_MODE_TICO_D_PLAY_MODE 0x1
#define TICO_DECODER_TICO_D_PROFILE_TICO_D_PROFILE_OFFSET 0
#define TICO_DECODER_TICO_D_PROFILE_TICO_D_PROFILE_MASK 0x3
#define TICO_DECODER_TICO_D_LINE_DURATION_TICO_D_LINE_DURATION_OFFSET 0
#define TICO_DECODER_TICO_D_LINE_DURATION_TICO_D_LINE_DURATION_MASK 0xFFFF
#define TICO_DECODER_TICO_D_IMG_SIZE_TICO_D_LINE_DURATION_OFFSET 0
#define TICO_DECODER_TICO_D_IMG_SIZE_TICO_D_LINE_DURATION_MASK 0xFFFFFFFF
#endif /* _TICO_DECODER_REGS_H_ */

/* end */
