/*Icron Technologies ***** Copyright 2015 All Rights Reserved. ******/
/**/
/**** This file is auto generated by IDesignSpec (http://www.agnisys.com) . Please do not edit this file. ****/
/* created by        : Mohsen Nahvi*/
/* generated by      : Mohsen.Nahvi*/
/* generated from    : C:\cygwin64\home\Mohsen.Nahvi\blackbird_network_develop\m_xusb3\regs\ids\xusb3_regs.docx*/
/* IDesignSpec rev   : 6.8.10.0*/

/**** This code is generated with following settings ****/
/* Reg Width                  : 32*/
/* Address Unit               : 8*/
/* C++ Types int              : uint%d_t*/
/* Bus Type                   : APB*/
/* BigEndian                  : true*/
/* LittleEndian               : true*/
/* Dist. Decode and Readback  : false*/
/*--------------------------------------------------------------------------------------------------------------- */

/*block : xusb3 */

#ifndef _XUSB3_REGS_H_
#define _XUSB3_REGS_H_

#ifndef __ASSEMBLER__
#ifndef __ASSEMBLER__
typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv24 : 8;
            uint32_t major : 8;           /* 23:16 SW=ro HW=ro 0x4 */
            uint32_t minor : 8;           /* 15:8 SW=ro HW=ro 0x0 */
            uint32_t patch : 8;           /* 7:0 SW=ro HW=ro 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t patch : 8;           /* 0:7 SW=ro HW=ro 0x0 */
            uint32_t minor : 8;           /* 8:15 SW=ro HW=ro 0x0 */
            uint32_t major : 8;           /* 16:23 SW=ro HW=ro 0x4 */
            uint32_t resv24 : 8;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_version;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv30 : 2;
            uint32_t rx_buff_near_full_limit : 8;           /* 29:22 SW=rw HW=ro 0x80 */
            uint32_t upp_bypass : 1;           /* 21 SW=rw HW=ro 0x1 */
            uint32_t upp_is_present : 1;           /* 20 SW=ro HW=wo 0x0 */
            uint32_t split_dp_wait_time : 16;           /* 19:4 SW=rw HW=ro 0xFFFF */
            uint32_t split_dp_mode : 1;           /* 3 SW=rw HW=ro 0x0 */
            uint32_t allow_rx_buff_fill : 1;           /* 2 SW=rw HW=ro 0x0 */
            uint32_t drop_itp_pkts : 1;           /* 1 SW=rw HW=ro 0x0 */
            uint32_t upstream_port : 1;           /* 0 SW=rw HW=ro 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t upstream_port : 1;           /* 0 SW=rw HW=ro 0x0 */
            uint32_t drop_itp_pkts : 1;           /* 1 SW=rw HW=ro 0x0 */
            uint32_t allow_rx_buff_fill : 1;           /* 2 SW=rw HW=ro 0x0 */
            uint32_t split_dp_mode : 1;           /* 3 SW=rw HW=ro 0x0 */
            uint32_t split_dp_wait_time : 16;           /* 4:19 SW=rw HW=ro 0xFFFF */
            uint32_t upp_is_present : 1;           /* 20 SW=ro HW=wo 0x0 */
            uint32_t upp_bypass : 1;           /* 21 SW=rw HW=ro 0x1 */
            uint32_t rx_buff_near_full_limit : 8;           /* 22:29 SW=rw HW=ro 0x80 */
            uint32_t resv30 : 2;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_configuration;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv1 : 31;
            uint32_t remove_crdts : 1;           /* 0 SW=rw HW=ro 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t remove_crdts : 1;           /* 0 SW=rw HW=ro 0x0 */
            uint32_t resv1 : 31;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_control;

/*section : rx_partner_fifo */

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv24 : 8;
            uint32_t major : 8;           /* 23:16 SW=ro HW=na 0x1 */
            uint32_t minor : 8;           /* 15:8 SW=ro HW=na 0x1 */
            uint32_t patch : 8;           /* 7:0 SW=ro HW=na 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t patch : 8;           /* 0:7 SW=ro HW=na 0x0 */
            uint32_t minor : 8;           /* 8:15 SW=ro HW=na 0x1 */
            uint32_t major : 8;           /* 16:23 SW=ro HW=na 0x1 */
            uint32_t resv24 : 8;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_rx_partner_fifo_version;

/*section : write_engine */

/*section : config0 */

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv1 : 31;
            uint32_t wclr : 1;           /* 0 SW=rw HW=ro 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t wclr : 1;           /* 0 SW=rw HW=ro 0x0 */
            uint32_t resv1 : 31;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_rx_partner_fifo_write_engine_config0_clear;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv4 : 28;
            uint32_t drp_on_sop : 1;           /* 3 SW=rw HW=ro 0x0 */
            uint32_t drp_on_pkt_err : 1;           /* 2 SW=rw HW=ro 0x1 */
            uint32_t pkt_strm : 1;           /* 1 SW=rw HW=ro 0x0 */
            uint32_t flw_ctrl_en : 1;           /* 0 SW=rw HW=ro 0x1 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t flw_ctrl_en : 1;           /* 0 SW=rw HW=ro 0x1 */
            uint32_t pkt_strm : 1;           /* 1 SW=rw HW=ro 0x0 */
            uint32_t drp_on_pkt_err : 1;           /* 2 SW=rw HW=ro 0x1 */
            uint32_t drp_on_sop : 1;           /* 3 SW=rw HW=ro 0x0 */
            uint32_t resv4 : 28;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_rx_partner_fifo_write_engine_config0_mode;

typedef union {
    struct {
        uint32_t ntfy_lmt : 32;           /* 31:0 SW=rw HW=ro 0x0 */
    } bf;
    uint32_t  dw;
} xusb3_rx_partner_fifo_write_engine_config0_notify_limit;

typedef struct {
    xusb3_rx_partner_fifo_write_engine_config0_clear  clear;
    xusb3_rx_partner_fifo_write_engine_config0_mode  mode;
    xusb3_rx_partner_fifo_write_engine_config0_notify_limit  notify_limit;
    
} xusb3_rx_partner_fifo_write_engine_config0;


/*section : stats0 */

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv10 : 22;
            uint32_t flow_ctrl : 1;           /* 9 SW=rw HW=ro 0x0 */
            uint32_t drp_pkt_wr : 1;           /* 8 SW=rw HW=ro 0x0 */
            uint32_t drp_pkt_rd : 1;           /* 7 SW=rw HW=ro 0x0 */
            uint32_t wflush_act : 1;           /* 6 SW=rw HW=ro 0x0 */
            uint32_t pkt_sop_err : 1;           /* 5 SW=rw HW=ro 0x0 */
            uint32_t pkt_err : 1;           /* 4 SW=rw HW=ro 0x0 */
            uint32_t fifo_full_err : 1;           /* 3 SW=rw HW=ro 0x0 */
            uint32_t pkt_max_byte_cnt_err : 1;           /* 2 SW=rw HW=ro 0x0 */
            uint32_t pfifo_dcount : 1;           /* 1 SW=rw HW=ro 0x0 */
            uint32_t nfifo_dcount : 1;           /* 0 SW=rw HW=ro 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t nfifo_dcount : 1;           /* 0 SW=rw HW=ro 0x0 */
            uint32_t pfifo_dcount : 1;           /* 1 SW=rw HW=ro 0x0 */
            uint32_t pkt_max_byte_cnt_err : 1;           /* 2 SW=rw HW=ro 0x0 */
            uint32_t fifo_full_err : 1;           /* 3 SW=rw HW=ro 0x0 */
            uint32_t pkt_err : 1;           /* 4 SW=rw HW=ro 0x0 */
            uint32_t pkt_sop_err : 1;           /* 5 SW=rw HW=ro 0x0 */
            uint32_t wflush_act : 1;           /* 6 SW=rw HW=ro 0x0 */
            uint32_t drp_pkt_rd : 1;           /* 7 SW=rw HW=ro 0x0 */
            uint32_t drp_pkt_wr : 1;           /* 8 SW=rw HW=ro 0x0 */
            uint32_t flow_ctrl : 1;           /* 9 SW=rw HW=ro 0x0 */
            uint32_t resv10 : 22;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_rx_partner_fifo_write_engine_stats0_rd2clr_config;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv16 : 16;
            uint32_t nfifo_dcount : 16;           /* 15:0 SW=ro HW=wo 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t nfifo_dcount : 16;           /* 0:15 SW=ro HW=wo 0x0 */
            uint32_t resv16 : 16;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_rx_partner_fifo_write_engine_stats0_nfifo_dcount;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv16 : 16;
            uint32_t pfifo_dcount : 16;           /* 15:0 SW=ro HW=wo 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t pfifo_dcount : 16;           /* 0:15 SW=ro HW=wo 0x0 */
            uint32_t resv16 : 16;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_rx_partner_fifo_write_engine_stats0_pfifo_dcount;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv8 : 24;
            uint32_t pkt_max_byte_cnt_err : 8;           /* 7:0 SW=ro HW=wo 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t pkt_max_byte_cnt_err : 8;           /* 0:7 SW=ro HW=wo 0x0 */
            uint32_t resv8 : 24;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_rx_partner_fifo_write_engine_stats0_pkt_max_byte_cnt_err;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv8 : 24;
            uint32_t fifo_full_err : 8;           /* 7:0 SW=ro HW=wo 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t fifo_full_err : 8;           /* 0:7 SW=ro HW=wo 0x0 */
            uint32_t resv8 : 24;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_rx_partner_fifo_write_engine_stats0_fifo_full_err;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv8 : 24;
            uint32_t pkt_err : 8;           /* 7:0 SW=ro HW=wo 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t pkt_err : 8;           /* 0:7 SW=ro HW=wo 0x0 */
            uint32_t resv8 : 24;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_rx_partner_fifo_write_engine_stats0_pkt_err;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv8 : 24;
            uint32_t pkt_sop_err : 8;           /* 7:0 SW=ro HW=wo 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t pkt_sop_err : 8;           /* 0:7 SW=ro HW=wo 0x0 */
            uint32_t resv8 : 24;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_rx_partner_fifo_write_engine_stats0_pkt_sop_err;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv8 : 24;
            uint32_t wflush_act : 8;           /* 7:0 SW=ro HW=wo 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t wflush_act : 8;           /* 0:7 SW=ro HW=wo 0x0 */
            uint32_t resv8 : 24;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_rx_partner_fifo_write_engine_stats0_wflush_act;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv8 : 24;
            uint32_t drp_pkt_rd : 8;           /* 7:0 SW=ro HW=wo 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t drp_pkt_rd : 8;           /* 0:7 SW=ro HW=wo 0x0 */
            uint32_t resv8 : 24;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_rx_partner_fifo_write_engine_stats0_drp_pkt_rd;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv8 : 24;
            uint32_t drp_pkt_wr : 8;           /* 7:0 SW=ro HW=wo 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t drp_pkt_wr : 8;           /* 0:7 SW=ro HW=wo 0x0 */
            uint32_t resv8 : 24;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_rx_partner_fifo_write_engine_stats0_drp_pkt_wr;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv16 : 16;
            uint32_t flow_ctrl : 16;           /* 15:0 SW=ro HW=wo 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t flow_ctrl : 16;           /* 0:15 SW=ro HW=wo 0x0 */
            uint32_t resv16 : 16;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_rx_partner_fifo_write_engine_stats0_flow_ctrl;

typedef struct {
    xusb3_rx_partner_fifo_write_engine_stats0_rd2clr_config  rd2clr_config;
    xusb3_rx_partner_fifo_write_engine_stats0_nfifo_dcount  nfifo_dcount;
    xusb3_rx_partner_fifo_write_engine_stats0_pfifo_dcount  pfifo_dcount;
    xusb3_rx_partner_fifo_write_engine_stats0_pkt_max_byte_cnt_err  pkt_max_byte_cnt_err;
    xusb3_rx_partner_fifo_write_engine_stats0_fifo_full_err  fifo_full_err;
    xusb3_rx_partner_fifo_write_engine_stats0_pkt_err  pkt_err;
    xusb3_rx_partner_fifo_write_engine_stats0_pkt_sop_err  pkt_sop_err;
    xusb3_rx_partner_fifo_write_engine_stats0_wflush_act  wflush_act;
    xusb3_rx_partner_fifo_write_engine_stats0_drp_pkt_rd  drp_pkt_rd;
    xusb3_rx_partner_fifo_write_engine_stats0_drp_pkt_wr  drp_pkt_wr;
    xusb3_rx_partner_fifo_write_engine_stats0_flow_ctrl  flow_ctrl;
    
} xusb3_rx_partner_fifo_write_engine_stats0;


typedef struct {
    
    union {
        xusb3_rx_partner_fifo_write_engine_config0 s;
        uint8_t filler[0xC];
    } config0;
    
    union {
        xusb3_rx_partner_fifo_write_engine_stats0 s;
        uint8_t filler[0x2C];
    } stats0;
    
} xusb3_rx_partner_fifo_write_engine;


/*section : read_engine */

/*section : config0 */

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv1 : 31;
            uint32_t rclr : 1;           /* 0 SW=rw HW=ro 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t rclr : 1;           /* 0 SW=rw HW=ro 0x0 */
            uint32_t resv1 : 31;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_rx_partner_fifo_read_engine_config0_clear;

typedef struct {
    xusb3_rx_partner_fifo_read_engine_config0_clear  clear;
    
} xusb3_rx_partner_fifo_read_engine_config0;


/*section : stats0 */

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv3 : 29;
            uint32_t flow_ctrl : 1;           /* 2 SW=rw HW=ro 0x0 */
            uint32_t drp_pkt : 1;           /* 1 SW=rw HW=ro 0x0 */
            uint32_t rflush_act : 1;           /* 0 SW=rw HW=ro 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t rflush_act : 1;           /* 0 SW=rw HW=ro 0x0 */
            uint32_t drp_pkt : 1;           /* 1 SW=rw HW=ro 0x0 */
            uint32_t flow_ctrl : 1;           /* 2 SW=rw HW=ro 0x0 */
            uint32_t resv3 : 29;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_rx_partner_fifo_read_engine_stats0_rd2clr_config;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv8 : 24;
            uint32_t rflush_act : 8;           /* 7:0 SW=ro HW=wo 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t rflush_act : 8;           /* 0:7 SW=ro HW=wo 0x0 */
            uint32_t resv8 : 24;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_rx_partner_fifo_read_engine_stats0_rflush_act;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv8 : 24;
            uint32_t drp_pkt : 8;           /* 7:0 SW=ro HW=wo 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t drp_pkt : 8;           /* 0:7 SW=ro HW=wo 0x0 */
            uint32_t resv8 : 24;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_rx_partner_fifo_read_engine_stats0_drp_pkt;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv16 : 16;
            uint32_t flow_ctrl : 16;           /* 15:0 SW=ro HW=wo 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t flow_ctrl : 16;           /* 0:15 SW=ro HW=wo 0x0 */
            uint32_t resv16 : 16;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_rx_partner_fifo_read_engine_stats0_flow_ctrl;

typedef struct {
    xusb3_rx_partner_fifo_read_engine_stats0_rd2clr_config  rd2clr_config;
    xusb3_rx_partner_fifo_read_engine_stats0_rflush_act  rflush_act;
    xusb3_rx_partner_fifo_read_engine_stats0_drp_pkt  drp_pkt;
    xusb3_rx_partner_fifo_read_engine_stats0_flow_ctrl  flow_ctrl;
    
} xusb3_rx_partner_fifo_read_engine_stats0;


typedef struct {
    
    union {
        xusb3_rx_partner_fifo_read_engine_config0 s;
        uint8_t filler[0x4];
    } config0;
    
    union {
        xusb3_rx_partner_fifo_read_engine_stats0 s;
        uint8_t filler[0x10];
    } stats0;
    
} xusb3_rx_partner_fifo_read_engine;


typedef struct {
    xusb3_rx_partner_fifo_version  version;
    
    union {
        xusb3_rx_partner_fifo_write_engine s;
        uint8_t filler[0x38];
    } write_engine;
    
    union {
        xusb3_rx_partner_fifo_read_engine s;
        uint8_t filler[0x14];
    } read_engine;
    
} xusb3_rx_partner_fifo;


/*section : stats0 */

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv13 : 19;
            uint32_t not_rdy_pkt_drp : 1;           /* 12 SW=rw HW=ro 0x0 */
            uint32_t timedout_2join_dpp : 1;           /* 11 SW=rw HW=ro 0x0 */
            uint32_t rcvd_lone_dph : 1;           /* 10 SW=rw HW=ro 0x0 */
            uint32_t drop_lone_dpp : 1;           /* 9 SW=rw HW=ro 0x0 */
            uint32_t dwn_stream_busy_drp : 1;           /* 8 SW=rw HW=ro 0x0 */
            uint32_t unknown_pkt_drp : 1;           /* 7 SW=rw HW=ro 0x0 */
            uint32_t from_link_in_eop : 1;           /* 6 SW=rw HW=ro 0x0 */
            uint32_t from_link_in_sop : 1;           /* 5 SW=rw HW=ro 0x0 */
            uint32_t to_link_out_eop : 1;           /* 4 SW=rw HW=ro 0x0 */
            uint32_t to_link_out_sop : 1;           /* 3 SW=rw HW=ro 0x0 */
            uint32_t from_phy_in_eop : 1;           /* 2 SW=rw HW=ro 0x0 */
            uint32_t from_phy_in_sop : 1;           /* 1 SW=rw HW=ro 0x0 */
            uint32_t link_partner_ptp_violated : 1;           /* 0 SW=rw HW=ro 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t link_partner_ptp_violated : 1;           /* 0 SW=rw HW=ro 0x0 */
            uint32_t from_phy_in_sop : 1;           /* 1 SW=rw HW=ro 0x0 */
            uint32_t from_phy_in_eop : 1;           /* 2 SW=rw HW=ro 0x0 */
            uint32_t to_link_out_sop : 1;           /* 3 SW=rw HW=ro 0x0 */
            uint32_t to_link_out_eop : 1;           /* 4 SW=rw HW=ro 0x0 */
            uint32_t from_link_in_sop : 1;           /* 5 SW=rw HW=ro 0x0 */
            uint32_t from_link_in_eop : 1;           /* 6 SW=rw HW=ro 0x0 */
            uint32_t unknown_pkt_drp : 1;           /* 7 SW=rw HW=ro 0x0 */
            uint32_t dwn_stream_busy_drp : 1;           /* 8 SW=rw HW=ro 0x0 */
            uint32_t drop_lone_dpp : 1;           /* 9 SW=rw HW=ro 0x0 */
            uint32_t rcvd_lone_dph : 1;           /* 10 SW=rw HW=ro 0x0 */
            uint32_t timedout_2join_dpp : 1;           /* 11 SW=rw HW=ro 0x0 */
            uint32_t not_rdy_pkt_drp : 1;           /* 12 SW=rw HW=ro 0x0 */
            uint32_t resv13 : 19;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_stats0_rd2clr_config;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv8 : 24;
            uint32_t link_partner_ptp_violated : 8;           /* 7:0 SW=ro HW=wo 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t link_partner_ptp_violated : 8;           /* 0:7 SW=ro HW=wo 0x0 */
            uint32_t resv8 : 24;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_stats0_link_partner_ptp_violated;

typedef union {
    struct {
        uint32_t from_phy_in_sop : 32;           /* 31:0 SW=ro HW=wo 0x0 */
    } bf;
    uint32_t  dw;
} xusb3_stats0_from_phy_in_sop;

typedef union {
    struct {
        uint32_t from_phy_in_eop : 32;           /* 31:0 SW=ro HW=wo 0x0 */
    } bf;
    uint32_t  dw;
} xusb3_stats0_from_phy_in_eop;

typedef union {
    struct {
        uint32_t to_link_out_sop : 32;           /* 31:0 SW=ro HW=wo 0x0 */
    } bf;
    uint32_t  dw;
} xusb3_stats0_to_link_out_sop;

typedef union {
    struct {
        uint32_t to_link_out_eop : 32;           /* 31:0 SW=ro HW=wo 0x0 */
    } bf;
    uint32_t  dw;
} xusb3_stats0_to_link_out_eop;

typedef union {
    struct {
        uint32_t from_link_in_sop : 32;           /* 31:0 SW=ro HW=wo 0x0 */
    } bf;
    uint32_t  dw;
} xusb3_stats0_from_link_in_sop;

typedef union {
    struct {
        uint32_t from_link_in_eop : 32;           /* 31:0 SW=ro HW=wo 0x0 */
    } bf;
    uint32_t  dw;
} xusb3_stats0_from_link_in_eop;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv16 : 16;
            uint32_t unknown_pkt_drp : 16;           /* 15:0 SW=ro HW=wo 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t unknown_pkt_drp : 16;           /* 0:15 SW=ro HW=wo 0x0 */
            uint32_t resv16 : 16;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_stats0_unknown_pkt_drp;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv16 : 16;
            uint32_t dwn_stream_busy_drp : 16;           /* 15:0 SW=ro HW=wo 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t dwn_stream_busy_drp : 16;           /* 0:15 SW=ro HW=wo 0x0 */
            uint32_t resv16 : 16;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_stats0_dwn_stream_busy_drp;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv16 : 16;
            uint32_t drop_lone_dpp : 16;           /* 15:0 SW=ro HW=wo 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t drop_lone_dpp : 16;           /* 0:15 SW=ro HW=wo 0x0 */
            uint32_t resv16 : 16;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_stats0_drop_lone_dpp;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv16 : 16;
            uint32_t rcvd_lone_dph : 16;           /* 15:0 SW=ro HW=wo 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t rcvd_lone_dph : 16;           /* 0:15 SW=ro HW=wo 0x0 */
            uint32_t resv16 : 16;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_stats0_rcvd_lone_dph;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv16 : 16;
            uint32_t timedout_2join_dpp : 16;           /* 15:0 SW=ro HW=wo 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t timedout_2join_dpp : 16;           /* 0:15 SW=ro HW=wo 0x0 */
            uint32_t resv16 : 16;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_stats0_timedout_2join_dpp;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv16 : 16;
            uint32_t not_rdy_pkt_drp : 16;           /* 15:0 SW=ro HW=wo 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t not_rdy_pkt_drp : 16;           /* 0:15 SW=ro HW=wo 0x0 */
            uint32_t resv16 : 16;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_stats0_not_rdy_pkt_drp;

typedef struct {
    xusb3_stats0_rd2clr_config  rd2clr_config;
    xusb3_stats0_link_partner_ptp_violated  link_partner_ptp_violated;
    xusb3_stats0_from_phy_in_sop  from_phy_in_sop;
    xusb3_stats0_from_phy_in_eop  from_phy_in_eop;
    xusb3_stats0_to_link_out_sop  to_link_out_sop;
    xusb3_stats0_to_link_out_eop  to_link_out_eop;
    xusb3_stats0_from_link_in_sop  from_link_in_sop;
    xusb3_stats0_from_link_in_eop  from_link_in_eop;
    xusb3_stats0_unknown_pkt_drp  unknown_pkt_drp;
    xusb3_stats0_dwn_stream_busy_drp  dwn_stream_busy_drp;
    xusb3_stats0_drop_lone_dpp  drop_lone_dpp;
    xusb3_stats0_rcvd_lone_dph  rcvd_lone_dph;
    xusb3_stats0_timedout_2join_dpp  timedout_2join_dpp;
    xusb3_stats0_not_rdy_pkt_drp  not_rdy_pkt_drp;
    
    
    
} xusb3_stats0;


/*section : ptp_guard_2core */

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv24 : 8;
            uint32_t major : 8;           /* 23:16 SW=ro HW=na 0x3 */
            uint32_t minor : 8;           /* 15:8 SW=ro HW=na 0x3 */
            uint32_t patch : 8;           /* 7:0 SW=ro HW=na 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t patch : 8;           /* 0:7 SW=ro HW=na 0x0 */
            uint32_t minor : 8;           /* 8:15 SW=ro HW=na 0x3 */
            uint32_t major : 8;           /* 16:23 SW=ro HW=na 0x3 */
            uint32_t resv24 : 8;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_ptp_guard_2core_version;

/*section : config0 */

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv2 : 30;
            uint32_t implemented : 1;           /* 1 SW=ro HW=wo 0x0 */
            uint32_t activate : 1;           /* 0 SW=rw HW=ro 0x1 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t activate : 1;           /* 0 SW=rw HW=ro 0x1 */
            uint32_t implemented : 1;           /* 1 SW=ro HW=wo 0x0 */
            uint32_t resv2 : 30;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_ptp_guard_2core_config0_fix_ptp_violations;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv20 : 12;
            uint32_t max_cycle_mode : 4;           /* 19:16 SW=rw HW=ro 0x3 */
            uint32_t max_cycles : 16;           /* 15:0 SW=rw HW=ro 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t max_cycles : 16;           /* 0:15 SW=rw HW=ro 0x0 */
            uint32_t max_cycle_mode : 4;           /* 16:19 SW=rw HW=ro 0x3 */
            uint32_t resv20 : 12;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_ptp_guard_2core_config0_max_cycles;

typedef struct {
    xusb3_ptp_guard_2core_config0_fix_ptp_violations  fix_ptp_violations;
    xusb3_ptp_guard_2core_config0_max_cycles  max_cycles;
    
} xusb3_ptp_guard_2core_config0;


/*section : stats0 */

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv3 : 29;
            uint32_t max_cycle_err : 1;           /* 2 SW=rw HW=ro 0x0 */
            uint32_t missing_eop_err : 1;           /* 1 SW=rw HW=ro 0x0 */
            uint32_t missing_sop_err : 1;           /* 0 SW=rw HW=ro 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t missing_sop_err : 1;           /* 0 SW=rw HW=ro 0x0 */
            uint32_t missing_eop_err : 1;           /* 1 SW=rw HW=ro 0x0 */
            uint32_t max_cycle_err : 1;           /* 2 SW=rw HW=ro 0x0 */
            uint32_t resv3 : 29;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_ptp_guard_2core_stats0_rd2clr_config;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv16 : 16;
            uint32_t missing_sop_err : 16;           /* 15:0 SW=ro HW=wo 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t missing_sop_err : 16;           /* 0:15 SW=ro HW=wo 0x0 */
            uint32_t resv16 : 16;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_ptp_guard_2core_stats0_missing_sop_err;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv16 : 16;
            uint32_t missing_eop_err : 16;           /* 15:0 SW=ro HW=wo 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t missing_eop_err : 16;           /* 0:15 SW=ro HW=wo 0x0 */
            uint32_t resv16 : 16;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_ptp_guard_2core_stats0_missing_eop_err;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv16 : 16;
            uint32_t max_cycle_err : 16;           /* 15:0 SW=ro HW=wo 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t max_cycle_err : 16;           /* 0:15 SW=ro HW=wo 0x0 */
            uint32_t resv16 : 16;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_ptp_guard_2core_stats0_max_cycle_err;

typedef struct {
    xusb3_ptp_guard_2core_stats0_rd2clr_config  rd2clr_config;
    xusb3_ptp_guard_2core_stats0_missing_sop_err  missing_sop_err;
    xusb3_ptp_guard_2core_stats0_missing_eop_err  missing_eop_err;
    xusb3_ptp_guard_2core_stats0_max_cycle_err  max_cycle_err;
    
} xusb3_ptp_guard_2core_stats0;


/*section : irq0 */

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv3 : 29;
            uint32_t max_cycle_err : 1;           /* 2 SW=rw HW=na 0x0 */
            uint32_t missing_eop_err : 1;           /* 1 SW=rw HW=na 0x0 */
            uint32_t missing_sop_err : 1;           /* 0 SW=rw HW=na 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t missing_sop_err : 1;           /* 0 SW=rw HW=na 0x0 */
            uint32_t missing_eop_err : 1;           /* 1 SW=rw HW=na 0x0 */
            uint32_t max_cycle_err : 1;           /* 2 SW=rw HW=na 0x0 */
            uint32_t resv3 : 29;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_ptp_guard_2core_irq0_enable;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv3 : 29;
            uint32_t max_cycle_err : 1;           /* 2 SW=r/w1c HW=wo 0x0 */
            uint32_t missing_eop_err : 1;           /* 1 SW=r/w1c HW=wo 0x0 */
            uint32_t missing_sop_err : 1;           /* 0 SW=r/w1c HW=wo 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t missing_sop_err : 1;           /* 0 SW=r/w1c HW=wo 0x0 */
            uint32_t missing_eop_err : 1;           /* 1 SW=r/w1c HW=wo 0x0 */
            uint32_t max_cycle_err : 1;           /* 2 SW=r/w1c HW=wo 0x0 */
            uint32_t resv3 : 29;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_ptp_guard_2core_irq0_pending;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv3 : 29;
            uint32_t max_cycle_err : 1;           /* 2 SW=ro HW=na 0x0 */
            uint32_t missing_eop_err : 1;           /* 1 SW=ro HW=na 0x0 */
            uint32_t missing_sop_err : 1;           /* 0 SW=ro HW=na 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t missing_sop_err : 1;           /* 0 SW=ro HW=na 0x0 */
            uint32_t missing_eop_err : 1;           /* 1 SW=ro HW=na 0x0 */
            uint32_t max_cycle_err : 1;           /* 2 SW=ro HW=na 0x0 */
            uint32_t resv3 : 29;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_ptp_guard_2core_irq0_pending_irq;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv3 : 29;
            uint32_t max_cycle_err : 1;           /* 2 SW=ro HW=wo 0x0 */
            uint32_t missing_eop_err : 1;           /* 1 SW=ro HW=wo 0x0 */
            uint32_t missing_sop_err : 1;           /* 0 SW=ro HW=wo 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t missing_sop_err : 1;           /* 0 SW=ro HW=wo 0x0 */
            uint32_t missing_eop_err : 1;           /* 1 SW=ro HW=wo 0x0 */
            uint32_t max_cycle_err : 1;           /* 2 SW=ro HW=wo 0x0 */
            uint32_t resv3 : 29;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_ptp_guard_2core_irq0_raw;

typedef struct {
    xusb3_ptp_guard_2core_irq0_enable  enable;
    xusb3_ptp_guard_2core_irq0_pending  pending;
    xusb3_ptp_guard_2core_irq0_pending_irq  pending_irq;
    xusb3_ptp_guard_2core_irq0_raw  raw;
    
} xusb3_ptp_guard_2core_irq0;


typedef struct {
    xusb3_ptp_guard_2core_version  version;
    
    union {
        xusb3_ptp_guard_2core_config0 s;
        uint8_t filler[0x8];
    } config0;
    
    union {
        xusb3_ptp_guard_2core_stats0 s;
        uint8_t filler[0x10];
    } stats0;
    
    union {
        xusb3_ptp_guard_2core_irq0 s;
        uint8_t filler[0x10];
    } irq0;
    
} xusb3_ptp_guard_2core;


/*section : buff_2ulp */

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv1 : 31;
            uint32_t clr : 1;           /* 0 SW=rw HW=ro 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t clr : 1;           /* 0 SW=rw HW=ro 0x0 */
            uint32_t resv1 : 31;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_buff_2ulp_control;

/*section : stats0 */

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv2 : 30;
            uint32_t pfifo_dcount : 1;           /* 1 SW=rw HW=ro 0x0 */
            uint32_t nfifo_dcount : 1;           /* 0 SW=rw HW=ro 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t nfifo_dcount : 1;           /* 0 SW=rw HW=ro 0x0 */
            uint32_t pfifo_dcount : 1;           /* 1 SW=rw HW=ro 0x0 */
            uint32_t resv2 : 30;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_buff_2ulp_stats0_rd2clr_config;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv16 : 16;
            uint32_t nfifo_dcount : 16;           /* 15:0 SW=ro HW=wo 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t nfifo_dcount : 16;           /* 0:15 SW=ro HW=wo 0x0 */
            uint32_t resv16 : 16;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_buff_2ulp_stats0_nfifo_dcount;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv16 : 16;
            uint32_t pfifo_dcount : 16;           /* 15:0 SW=ro HW=wo 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t pfifo_dcount : 16;           /* 0:15 SW=ro HW=wo 0x0 */
            uint32_t resv16 : 16;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_buff_2ulp_stats0_pfifo_dcount;

typedef struct {
    xusb3_buff_2ulp_stats0_rd2clr_config  rd2clr_config;
    xusb3_buff_2ulp_stats0_nfifo_dcount  nfifo_dcount;
    xusb3_buff_2ulp_stats0_pfifo_dcount  pfifo_dcount;
    
    
    
} xusb3_buff_2ulp_stats0;


typedef struct {
    xusb3_buff_2ulp_control  control;
    
    union {
        xusb3_buff_2ulp_stats0 s;
        uint8_t filler[0xC];
    } stats0;
    
    
    
} xusb3_buff_2ulp;


/*section : buff_2upp */

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv1 : 31;
            uint32_t clr : 1;           /* 0 SW=rw HW=ro 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t clr : 1;           /* 0 SW=rw HW=ro 0x0 */
            uint32_t resv1 : 31;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_buff_2upp_control;

/*section : stats0 */

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv2 : 30;
            uint32_t pfifo_scount : 1;           /* 1 SW=rw HW=ro 0x0 */
            uint32_t nfifo_scount : 1;           /* 0 SW=rw HW=ro 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t nfifo_scount : 1;           /* 0 SW=rw HW=ro 0x0 */
            uint32_t pfifo_scount : 1;           /* 1 SW=rw HW=ro 0x0 */
            uint32_t resv2 : 30;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_buff_2upp_stats0_rd2clr_config;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv16 : 16;
            uint32_t nfifo_scount : 16;           /* 15:0 SW=ro HW=wo 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t nfifo_scount : 16;           /* 0:15 SW=ro HW=wo 0x0 */
            uint32_t resv16 : 16;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_buff_2upp_stats0_nfifo_scount;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv16 : 16;
            uint32_t pfifo_scount : 16;           /* 15:0 SW=ro HW=wo 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t pfifo_scount : 16;           /* 0:15 SW=ro HW=wo 0x0 */
            uint32_t resv16 : 16;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_buff_2upp_stats0_pfifo_scount;

typedef struct {
    xusb3_buff_2upp_stats0_rd2clr_config  rd2clr_config;
    xusb3_buff_2upp_stats0_nfifo_scount  nfifo_scount;
    xusb3_buff_2upp_stats0_pfifo_scount  pfifo_scount;
    
    
    
} xusb3_buff_2upp_stats0;


typedef struct {
    xusb3_buff_2upp_control  control;
    
    union {
        xusb3_buff_2upp_stats0 s;
        uint8_t filler[0xC];
    } stats0;
    
    
    
} xusb3_buff_2upp;


/*section : irq0 */

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv1 : 31;
            uint32_t link_partner_ptp_violated : 1;           /* 0 SW=rw HW=na 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t link_partner_ptp_violated : 1;           /* 0 SW=rw HW=na 0x0 */
            uint32_t resv1 : 31;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_irq0_enable;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv1 : 31;
            uint32_t link_partner_ptp_violated : 1;           /* 0 SW=r/w1c HW=wo 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t link_partner_ptp_violated : 1;           /* 0 SW=r/w1c HW=wo 0x0 */
            uint32_t resv1 : 31;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_irq0_pending;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv1 : 31;
            uint32_t link_partner_ptp_violated : 1;           /* 0 SW=ro HW=na 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t link_partner_ptp_violated : 1;           /* 0 SW=ro HW=na 0x0 */
            uint32_t resv1 : 31;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_irq0_pending_irq;

typedef union {
    #ifdef IDS_BIG_ENDIAN
        struct {
            
            uint32_t resv1 : 31;
            uint32_t link_partner_ptp_violated : 1;           /* 0 SW=ro HW=wo 0x0 */
        } bf;
        
    #else     /* IDS_LITTLE_ENDIAN */
        struct {
            uint32_t link_partner_ptp_violated : 1;           /* 0 SW=ro HW=wo 0x0 */
            uint32_t resv1 : 31;
        } bf;
        
    #endif
    uint32_t  dw;
} xusb3_irq0_raw;

typedef struct {
    xusb3_irq0_enable  enable;
    xusb3_irq0_pending  pending;
    xusb3_irq0_pending_irq  pending_irq;
    xusb3_irq0_raw  raw;
    
    
    
} xusb3_irq0;


typedef struct {
    xusb3_version  version;
    xusb3_configuration  configuration;
    xusb3_control  control;
    
    union {
        xusb3_rx_partner_fifo s;
        uint8_t filler[0x50];
    } rx_partner_fifo;
    
    union {
        xusb3_stats0 s;
        uint8_t filler[0x38];
    } stats0;
    
    union {
        xusb3_ptp_guard_2core s;
        uint8_t filler[0x2C];
    } ptp_guard_2core;
    
    union {
        xusb3_buff_2ulp s;
        uint8_t filler[0x10];
    } buff_2ulp;
    
    union {
        xusb3_buff_2upp s;
        uint8_t filler[0x10];
    } buff_2upp;
    
    union {
        xusb3_irq0 s;
        uint8_t filler[0x10];
    } irq0;
    
    
    uint8_t filler11[0x110];
    
    
} xusb3_s;


#endif   //__ASSEMBLER__


#endif // __ASSEMBLER__
#define xusb3_version_READMASK 0xFFFFFF
#define xusb3_version_WRITEMASK 0x0
#define xusb3_version_VOLATILEMASK 0x0
#define xusb3_version_RESETMASK 0xFFFFFF
#define xusb3_version_DEFAULT 0x00040000

#define xusb3_configuration_READMASK 0x3FFFFFFF
#define xusb3_configuration_WRITEMASK 0x3FEFFFFF
#define xusb3_configuration_VOLATILEMASK 0x100000
#define xusb3_configuration_RESETMASK 0x3FFFFFFF
#define xusb3_configuration_DEFAULT 0x202FFFF0

#define xusb3_control_READMASK 0x1
#define xusb3_control_WRITEMASK 0x1
#define xusb3_control_VOLATILEMASK 0x0
#define xusb3_control_RESETMASK 0x1
#define xusb3_control_DEFAULT 0x00000000

#define xusb3_rx_partner_fifo_version_READMASK 0xFFFFFF
#define xusb3_rx_partner_fifo_version_WRITEMASK 0x0
#define xusb3_rx_partner_fifo_version_VOLATILEMASK 0x0
#define xusb3_rx_partner_fifo_version_RESETMASK 0xFFFFFF
#define xusb3_rx_partner_fifo_version_DEFAULT 0x00010100

#define xusb3_rx_partner_fifo_write_engine_config0_clear_READMASK 0x1
#define xusb3_rx_partner_fifo_write_engine_config0_clear_WRITEMASK 0x1
#define xusb3_rx_partner_fifo_write_engine_config0_clear_VOLATILEMASK 0x0
#define xusb3_rx_partner_fifo_write_engine_config0_clear_RESETMASK 0x1
#define xusb3_rx_partner_fifo_write_engine_config0_clear_DEFAULT 0x00000000

#define xusb3_rx_partner_fifo_write_engine_config0_mode_READMASK 0xF
#define xusb3_rx_partner_fifo_write_engine_config0_mode_WRITEMASK 0xF
#define xusb3_rx_partner_fifo_write_engine_config0_mode_VOLATILEMASK 0x0
#define xusb3_rx_partner_fifo_write_engine_config0_mode_RESETMASK 0xF
#define xusb3_rx_partner_fifo_write_engine_config0_mode_DEFAULT 0x00000005

#define xusb3_rx_partner_fifo_write_engine_config0_notify_limit_READMASK 0xFFFFFFFF
#define xusb3_rx_partner_fifo_write_engine_config0_notify_limit_WRITEMASK 0xFFFFFFFF
#define xusb3_rx_partner_fifo_write_engine_config0_notify_limit_VOLATILEMASK 0x0
#define xusb3_rx_partner_fifo_write_engine_config0_notify_limit_RESETMASK 0xFFFFFFFF
#define xusb3_rx_partner_fifo_write_engine_config0_notify_limit_DEFAULT 0x00000000

#define xusb3_rx_partner_fifo_write_engine_stats0_rd2clr_config_READMASK 0x3FF
#define xusb3_rx_partner_fifo_write_engine_stats0_rd2clr_config_WRITEMASK 0x3FF
#define xusb3_rx_partner_fifo_write_engine_stats0_rd2clr_config_VOLATILEMASK 0x0
#define xusb3_rx_partner_fifo_write_engine_stats0_rd2clr_config_RESETMASK 0x3FF
#define xusb3_rx_partner_fifo_write_engine_stats0_rd2clr_config_DEFAULT 0x00000000

#define xusb3_rx_partner_fifo_write_engine_stats0_nfifo_dcount_READMASK 0xFFFF
#define xusb3_rx_partner_fifo_write_engine_stats0_nfifo_dcount_WRITEMASK 0x0
#define xusb3_rx_partner_fifo_write_engine_stats0_nfifo_dcount_VOLATILEMASK 0xFFFF
#define xusb3_rx_partner_fifo_write_engine_stats0_nfifo_dcount_RESETMASK 0xFFFF
#define xusb3_rx_partner_fifo_write_engine_stats0_nfifo_dcount_DEFAULT 0x00000000

#define xusb3_rx_partner_fifo_write_engine_stats0_pfifo_dcount_READMASK 0xFFFF
#define xusb3_rx_partner_fifo_write_engine_stats0_pfifo_dcount_WRITEMASK 0x0
#define xusb3_rx_partner_fifo_write_engine_stats0_pfifo_dcount_VOLATILEMASK 0xFFFF
#define xusb3_rx_partner_fifo_write_engine_stats0_pfifo_dcount_RESETMASK 0xFFFF
#define xusb3_rx_partner_fifo_write_engine_stats0_pfifo_dcount_DEFAULT 0x00000000

#define xusb3_rx_partner_fifo_write_engine_stats0_pkt_max_byte_cnt_err_READMASK 0xFF
#define xusb3_rx_partner_fifo_write_engine_stats0_pkt_max_byte_cnt_err_WRITEMASK 0x0
#define xusb3_rx_partner_fifo_write_engine_stats0_pkt_max_byte_cnt_err_VOLATILEMASK 0xFF
#define xusb3_rx_partner_fifo_write_engine_stats0_pkt_max_byte_cnt_err_RESETMASK 0xFF
#define xusb3_rx_partner_fifo_write_engine_stats0_pkt_max_byte_cnt_err_DEFAULT 0x00000000

#define xusb3_rx_partner_fifo_write_engine_stats0_fifo_full_err_READMASK 0xFF
#define xusb3_rx_partner_fifo_write_engine_stats0_fifo_full_err_WRITEMASK 0x0
#define xusb3_rx_partner_fifo_write_engine_stats0_fifo_full_err_VOLATILEMASK 0xFF
#define xusb3_rx_partner_fifo_write_engine_stats0_fifo_full_err_RESETMASK 0xFF
#define xusb3_rx_partner_fifo_write_engine_stats0_fifo_full_err_DEFAULT 0x00000000

#define xusb3_rx_partner_fifo_write_engine_stats0_pkt_err_READMASK 0xFF
#define xusb3_rx_partner_fifo_write_engine_stats0_pkt_err_WRITEMASK 0x0
#define xusb3_rx_partner_fifo_write_engine_stats0_pkt_err_VOLATILEMASK 0xFF
#define xusb3_rx_partner_fifo_write_engine_stats0_pkt_err_RESETMASK 0xFF
#define xusb3_rx_partner_fifo_write_engine_stats0_pkt_err_DEFAULT 0x00000000

#define xusb3_rx_partner_fifo_write_engine_stats0_pkt_sop_err_READMASK 0xFF
#define xusb3_rx_partner_fifo_write_engine_stats0_pkt_sop_err_WRITEMASK 0x0
#define xusb3_rx_partner_fifo_write_engine_stats0_pkt_sop_err_VOLATILEMASK 0xFF
#define xusb3_rx_partner_fifo_write_engine_stats0_pkt_sop_err_RESETMASK 0xFF
#define xusb3_rx_partner_fifo_write_engine_stats0_pkt_sop_err_DEFAULT 0x00000000

#define xusb3_rx_partner_fifo_write_engine_stats0_wflush_act_READMASK 0xFF
#define xusb3_rx_partner_fifo_write_engine_stats0_wflush_act_WRITEMASK 0x0
#define xusb3_rx_partner_fifo_write_engine_stats0_wflush_act_VOLATILEMASK 0xFF
#define xusb3_rx_partner_fifo_write_engine_stats0_wflush_act_RESETMASK 0xFF
#define xusb3_rx_partner_fifo_write_engine_stats0_wflush_act_DEFAULT 0x00000000

#define xusb3_rx_partner_fifo_write_engine_stats0_drp_pkt_rd_READMASK 0xFF
#define xusb3_rx_partner_fifo_write_engine_stats0_drp_pkt_rd_WRITEMASK 0x0
#define xusb3_rx_partner_fifo_write_engine_stats0_drp_pkt_rd_VOLATILEMASK 0xFF
#define xusb3_rx_partner_fifo_write_engine_stats0_drp_pkt_rd_RESETMASK 0xFF
#define xusb3_rx_partner_fifo_write_engine_stats0_drp_pkt_rd_DEFAULT 0x00000000

#define xusb3_rx_partner_fifo_write_engine_stats0_drp_pkt_wr_READMASK 0xFF
#define xusb3_rx_partner_fifo_write_engine_stats0_drp_pkt_wr_WRITEMASK 0x0
#define xusb3_rx_partner_fifo_write_engine_stats0_drp_pkt_wr_VOLATILEMASK 0xFF
#define xusb3_rx_partner_fifo_write_engine_stats0_drp_pkt_wr_RESETMASK 0xFF
#define xusb3_rx_partner_fifo_write_engine_stats0_drp_pkt_wr_DEFAULT 0x00000000

#define xusb3_rx_partner_fifo_write_engine_stats0_flow_ctrl_READMASK 0xFFFF
#define xusb3_rx_partner_fifo_write_engine_stats0_flow_ctrl_WRITEMASK 0x0
#define xusb3_rx_partner_fifo_write_engine_stats0_flow_ctrl_VOLATILEMASK 0xFFFF
#define xusb3_rx_partner_fifo_write_engine_stats0_flow_ctrl_RESETMASK 0xFFFF
#define xusb3_rx_partner_fifo_write_engine_stats0_flow_ctrl_DEFAULT 0x00000000

#define xusb3_rx_partner_fifo_read_engine_config0_clear_READMASK 0x1
#define xusb3_rx_partner_fifo_read_engine_config0_clear_WRITEMASK 0x1
#define xusb3_rx_partner_fifo_read_engine_config0_clear_VOLATILEMASK 0x0
#define xusb3_rx_partner_fifo_read_engine_config0_clear_RESETMASK 0x1
#define xusb3_rx_partner_fifo_read_engine_config0_clear_DEFAULT 0x00000000

#define xusb3_rx_partner_fifo_read_engine_stats0_rd2clr_config_READMASK 0x7
#define xusb3_rx_partner_fifo_read_engine_stats0_rd2clr_config_WRITEMASK 0x7
#define xusb3_rx_partner_fifo_read_engine_stats0_rd2clr_config_VOLATILEMASK 0x0
#define xusb3_rx_partner_fifo_read_engine_stats0_rd2clr_config_RESETMASK 0x7
#define xusb3_rx_partner_fifo_read_engine_stats0_rd2clr_config_DEFAULT 0x00000000

#define xusb3_rx_partner_fifo_read_engine_stats0_rflush_act_READMASK 0xFF
#define xusb3_rx_partner_fifo_read_engine_stats0_rflush_act_WRITEMASK 0x0
#define xusb3_rx_partner_fifo_read_engine_stats0_rflush_act_VOLATILEMASK 0xFF
#define xusb3_rx_partner_fifo_read_engine_stats0_rflush_act_RESETMASK 0xFF
#define xusb3_rx_partner_fifo_read_engine_stats0_rflush_act_DEFAULT 0x00000000

#define xusb3_rx_partner_fifo_read_engine_stats0_drp_pkt_READMASK 0xFF
#define xusb3_rx_partner_fifo_read_engine_stats0_drp_pkt_WRITEMASK 0x0
#define xusb3_rx_partner_fifo_read_engine_stats0_drp_pkt_VOLATILEMASK 0xFF
#define xusb3_rx_partner_fifo_read_engine_stats0_drp_pkt_RESETMASK 0xFF
#define xusb3_rx_partner_fifo_read_engine_stats0_drp_pkt_DEFAULT 0x00000000

#define xusb3_rx_partner_fifo_read_engine_stats0_flow_ctrl_READMASK 0xFFFF
#define xusb3_rx_partner_fifo_read_engine_stats0_flow_ctrl_WRITEMASK 0x0
#define xusb3_rx_partner_fifo_read_engine_stats0_flow_ctrl_VOLATILEMASK 0xFFFF
#define xusb3_rx_partner_fifo_read_engine_stats0_flow_ctrl_RESETMASK 0xFFFF
#define xusb3_rx_partner_fifo_read_engine_stats0_flow_ctrl_DEFAULT 0x00000000

#define xusb3_stats0_rd2clr_config_READMASK 0x1FFF
#define xusb3_stats0_rd2clr_config_WRITEMASK 0x1FFF
#define xusb3_stats0_rd2clr_config_VOLATILEMASK 0x0
#define xusb3_stats0_rd2clr_config_RESETMASK 0x1FFF
#define xusb3_stats0_rd2clr_config_DEFAULT 0x00000000

#define xusb3_stats0_link_partner_ptp_violated_READMASK 0xFF
#define xusb3_stats0_link_partner_ptp_violated_WRITEMASK 0x0
#define xusb3_stats0_link_partner_ptp_violated_VOLATILEMASK 0xFF
#define xusb3_stats0_link_partner_ptp_violated_RESETMASK 0xFF
#define xusb3_stats0_link_partner_ptp_violated_DEFAULT 0x00000000

#define xusb3_stats0_from_phy_in_sop_READMASK 0xFFFFFFFF
#define xusb3_stats0_from_phy_in_sop_WRITEMASK 0x0
#define xusb3_stats0_from_phy_in_sop_VOLATILEMASK 0xFFFFFFFF
#define xusb3_stats0_from_phy_in_sop_RESETMASK 0xFFFFFFFF
#define xusb3_stats0_from_phy_in_sop_DEFAULT 0x00000000

#define xusb3_stats0_from_phy_in_eop_READMASK 0xFFFFFFFF
#define xusb3_stats0_from_phy_in_eop_WRITEMASK 0x0
#define xusb3_stats0_from_phy_in_eop_VOLATILEMASK 0xFFFFFFFF
#define xusb3_stats0_from_phy_in_eop_RESETMASK 0xFFFFFFFF
#define xusb3_stats0_from_phy_in_eop_DEFAULT 0x00000000

#define xusb3_stats0_to_link_out_sop_READMASK 0xFFFFFFFF
#define xusb3_stats0_to_link_out_sop_WRITEMASK 0x0
#define xusb3_stats0_to_link_out_sop_VOLATILEMASK 0xFFFFFFFF
#define xusb3_stats0_to_link_out_sop_RESETMASK 0xFFFFFFFF
#define xusb3_stats0_to_link_out_sop_DEFAULT 0x00000000

#define xusb3_stats0_to_link_out_eop_READMASK 0xFFFFFFFF
#define xusb3_stats0_to_link_out_eop_WRITEMASK 0x0
#define xusb3_stats0_to_link_out_eop_VOLATILEMASK 0xFFFFFFFF
#define xusb3_stats0_to_link_out_eop_RESETMASK 0xFFFFFFFF
#define xusb3_stats0_to_link_out_eop_DEFAULT 0x00000000

#define xusb3_stats0_from_link_in_sop_READMASK 0xFFFFFFFF
#define xusb3_stats0_from_link_in_sop_WRITEMASK 0x0
#define xusb3_stats0_from_link_in_sop_VOLATILEMASK 0xFFFFFFFF
#define xusb3_stats0_from_link_in_sop_RESETMASK 0xFFFFFFFF
#define xusb3_stats0_from_link_in_sop_DEFAULT 0x00000000

#define xusb3_stats0_from_link_in_eop_READMASK 0xFFFFFFFF
#define xusb3_stats0_from_link_in_eop_WRITEMASK 0x0
#define xusb3_stats0_from_link_in_eop_VOLATILEMASK 0xFFFFFFFF
#define xusb3_stats0_from_link_in_eop_RESETMASK 0xFFFFFFFF
#define xusb3_stats0_from_link_in_eop_DEFAULT 0x00000000

#define xusb3_stats0_unknown_pkt_drp_READMASK 0xFFFF
#define xusb3_stats0_unknown_pkt_drp_WRITEMASK 0x0
#define xusb3_stats0_unknown_pkt_drp_VOLATILEMASK 0xFFFF
#define xusb3_stats0_unknown_pkt_drp_RESETMASK 0xFFFF
#define xusb3_stats0_unknown_pkt_drp_DEFAULT 0x00000000

#define xusb3_stats0_dwn_stream_busy_drp_READMASK 0xFFFF
#define xusb3_stats0_dwn_stream_busy_drp_WRITEMASK 0x0
#define xusb3_stats0_dwn_stream_busy_drp_VOLATILEMASK 0xFFFF
#define xusb3_stats0_dwn_stream_busy_drp_RESETMASK 0xFFFF
#define xusb3_stats0_dwn_stream_busy_drp_DEFAULT 0x00000000

#define xusb3_stats0_drop_lone_dpp_READMASK 0xFFFF
#define xusb3_stats0_drop_lone_dpp_WRITEMASK 0x0
#define xusb3_stats0_drop_lone_dpp_VOLATILEMASK 0xFFFF
#define xusb3_stats0_drop_lone_dpp_RESETMASK 0xFFFF
#define xusb3_stats0_drop_lone_dpp_DEFAULT 0x00000000

#define xusb3_stats0_rcvd_lone_dph_READMASK 0xFFFF
#define xusb3_stats0_rcvd_lone_dph_WRITEMASK 0x0
#define xusb3_stats0_rcvd_lone_dph_VOLATILEMASK 0xFFFF
#define xusb3_stats0_rcvd_lone_dph_RESETMASK 0xFFFF
#define xusb3_stats0_rcvd_lone_dph_DEFAULT 0x00000000

#define xusb3_stats0_timedout_2join_dpp_READMASK 0xFFFF
#define xusb3_stats0_timedout_2join_dpp_WRITEMASK 0x0
#define xusb3_stats0_timedout_2join_dpp_VOLATILEMASK 0xFFFF
#define xusb3_stats0_timedout_2join_dpp_RESETMASK 0xFFFF
#define xusb3_stats0_timedout_2join_dpp_DEFAULT 0x00000000

#define xusb3_stats0_not_rdy_pkt_drp_READMASK 0xFFFF
#define xusb3_stats0_not_rdy_pkt_drp_WRITEMASK 0x0
#define xusb3_stats0_not_rdy_pkt_drp_VOLATILEMASK 0xFFFF
#define xusb3_stats0_not_rdy_pkt_drp_RESETMASK 0xFFFF
#define xusb3_stats0_not_rdy_pkt_drp_DEFAULT 0x00000000

#define xusb3_ptp_guard_2core_version_READMASK 0xFFFFFF
#define xusb3_ptp_guard_2core_version_WRITEMASK 0x0
#define xusb3_ptp_guard_2core_version_VOLATILEMASK 0x0
#define xusb3_ptp_guard_2core_version_RESETMASK 0xFFFFFF
#define xusb3_ptp_guard_2core_version_DEFAULT 0x00030300

#define xusb3_ptp_guard_2core_config0_fix_ptp_violations_READMASK 0x3
#define xusb3_ptp_guard_2core_config0_fix_ptp_violations_WRITEMASK 0x1
#define xusb3_ptp_guard_2core_config0_fix_ptp_violations_VOLATILEMASK 0x2
#define xusb3_ptp_guard_2core_config0_fix_ptp_violations_RESETMASK 0x3
#define xusb3_ptp_guard_2core_config0_fix_ptp_violations_DEFAULT 0x00000001

#define xusb3_ptp_guard_2core_config0_max_cycles_READMASK 0xFFFFF
#define xusb3_ptp_guard_2core_config0_max_cycles_WRITEMASK 0xFFFFF
#define xusb3_ptp_guard_2core_config0_max_cycles_VOLATILEMASK 0x0
#define xusb3_ptp_guard_2core_config0_max_cycles_RESETMASK 0xFFFFF
#define xusb3_ptp_guard_2core_config0_max_cycles_DEFAULT 0x00030000

#define xusb3_ptp_guard_2core_stats0_rd2clr_config_READMASK 0x7
#define xusb3_ptp_guard_2core_stats0_rd2clr_config_WRITEMASK 0x7
#define xusb3_ptp_guard_2core_stats0_rd2clr_config_VOLATILEMASK 0x0
#define xusb3_ptp_guard_2core_stats0_rd2clr_config_RESETMASK 0x7
#define xusb3_ptp_guard_2core_stats0_rd2clr_config_DEFAULT 0x00000000

#define xusb3_ptp_guard_2core_stats0_missing_sop_err_READMASK 0xFFFF
#define xusb3_ptp_guard_2core_stats0_missing_sop_err_WRITEMASK 0x0
#define xusb3_ptp_guard_2core_stats0_missing_sop_err_VOLATILEMASK 0xFFFF
#define xusb3_ptp_guard_2core_stats0_missing_sop_err_RESETMASK 0xFFFF
#define xusb3_ptp_guard_2core_stats0_missing_sop_err_DEFAULT 0x00000000

#define xusb3_ptp_guard_2core_stats0_missing_eop_err_READMASK 0xFFFF
#define xusb3_ptp_guard_2core_stats0_missing_eop_err_WRITEMASK 0x0
#define xusb3_ptp_guard_2core_stats0_missing_eop_err_VOLATILEMASK 0xFFFF
#define xusb3_ptp_guard_2core_stats0_missing_eop_err_RESETMASK 0xFFFF
#define xusb3_ptp_guard_2core_stats0_missing_eop_err_DEFAULT 0x00000000

#define xusb3_ptp_guard_2core_stats0_max_cycle_err_READMASK 0xFFFF
#define xusb3_ptp_guard_2core_stats0_max_cycle_err_WRITEMASK 0x0
#define xusb3_ptp_guard_2core_stats0_max_cycle_err_VOLATILEMASK 0xFFFF
#define xusb3_ptp_guard_2core_stats0_max_cycle_err_RESETMASK 0xFFFF
#define xusb3_ptp_guard_2core_stats0_max_cycle_err_DEFAULT 0x00000000

#define xusb3_ptp_guard_2core_irq0_enable_READMASK 0x7
#define xusb3_ptp_guard_2core_irq0_enable_WRITEMASK 0x7
#define xusb3_ptp_guard_2core_irq0_enable_VOLATILEMASK 0x0
#define xusb3_ptp_guard_2core_irq0_enable_RESETMASK 0x7
#define xusb3_ptp_guard_2core_irq0_enable_DEFAULT 0x00000000

#define xusb3_ptp_guard_2core_irq0_pending_READMASK 0x7
#define xusb3_ptp_guard_2core_irq0_pending_WRITEMASK 0x7
#define xusb3_ptp_guard_2core_irq0_pending_VOLATILEMASK 0x7
#define xusb3_ptp_guard_2core_irq0_pending_RESETMASK 0x7
#define xusb3_ptp_guard_2core_irq0_pending_DEFAULT 0x00000000

#define xusb3_ptp_guard_2core_irq0_pending_irq_READMASK 0x7
#define xusb3_ptp_guard_2core_irq0_pending_irq_WRITEMASK 0x0
#define xusb3_ptp_guard_2core_irq0_pending_irq_VOLATILEMASK 0x0
#define xusb3_ptp_guard_2core_irq0_pending_irq_RESETMASK 0x7
#define xusb3_ptp_guard_2core_irq0_pending_irq_DEFAULT 0x00000000

#define xusb3_ptp_guard_2core_irq0_raw_READMASK 0x7
#define xusb3_ptp_guard_2core_irq0_raw_WRITEMASK 0x0
#define xusb3_ptp_guard_2core_irq0_raw_VOLATILEMASK 0x7
#define xusb3_ptp_guard_2core_irq0_raw_RESETMASK 0x7
#define xusb3_ptp_guard_2core_irq0_raw_DEFAULT 0x00000000

#define xusb3_buff_2ulp_control_READMASK 0x1
#define xusb3_buff_2ulp_control_WRITEMASK 0x1
#define xusb3_buff_2ulp_control_VOLATILEMASK 0x0
#define xusb3_buff_2ulp_control_RESETMASK 0x1
#define xusb3_buff_2ulp_control_DEFAULT 0x00000000

#define xusb3_buff_2ulp_stats0_rd2clr_config_READMASK 0x3
#define xusb3_buff_2ulp_stats0_rd2clr_config_WRITEMASK 0x3
#define xusb3_buff_2ulp_stats0_rd2clr_config_VOLATILEMASK 0x0
#define xusb3_buff_2ulp_stats0_rd2clr_config_RESETMASK 0x3
#define xusb3_buff_2ulp_stats0_rd2clr_config_DEFAULT 0x00000000

#define xusb3_buff_2ulp_stats0_nfifo_dcount_READMASK 0xFFFF
#define xusb3_buff_2ulp_stats0_nfifo_dcount_WRITEMASK 0x0
#define xusb3_buff_2ulp_stats0_nfifo_dcount_VOLATILEMASK 0xFFFF
#define xusb3_buff_2ulp_stats0_nfifo_dcount_RESETMASK 0xFFFF
#define xusb3_buff_2ulp_stats0_nfifo_dcount_DEFAULT 0x00000000

#define xusb3_buff_2ulp_stats0_pfifo_dcount_READMASK 0xFFFF
#define xusb3_buff_2ulp_stats0_pfifo_dcount_WRITEMASK 0x0
#define xusb3_buff_2ulp_stats0_pfifo_dcount_VOLATILEMASK 0xFFFF
#define xusb3_buff_2ulp_stats0_pfifo_dcount_RESETMASK 0xFFFF
#define xusb3_buff_2ulp_stats0_pfifo_dcount_DEFAULT 0x00000000

#define xusb3_buff_2upp_control_READMASK 0x1
#define xusb3_buff_2upp_control_WRITEMASK 0x1
#define xusb3_buff_2upp_control_VOLATILEMASK 0x0
#define xusb3_buff_2upp_control_RESETMASK 0x1
#define xusb3_buff_2upp_control_DEFAULT 0x00000000

#define xusb3_buff_2upp_stats0_rd2clr_config_READMASK 0x3
#define xusb3_buff_2upp_stats0_rd2clr_config_WRITEMASK 0x3
#define xusb3_buff_2upp_stats0_rd2clr_config_VOLATILEMASK 0x0
#define xusb3_buff_2upp_stats0_rd2clr_config_RESETMASK 0x3
#define xusb3_buff_2upp_stats0_rd2clr_config_DEFAULT 0x00000000

#define xusb3_buff_2upp_stats0_nfifo_scount_READMASK 0xFFFF
#define xusb3_buff_2upp_stats0_nfifo_scount_WRITEMASK 0x0
#define xusb3_buff_2upp_stats0_nfifo_scount_VOLATILEMASK 0xFFFF
#define xusb3_buff_2upp_stats0_nfifo_scount_RESETMASK 0xFFFF
#define xusb3_buff_2upp_stats0_nfifo_scount_DEFAULT 0x00000000

#define xusb3_buff_2upp_stats0_pfifo_scount_READMASK 0xFFFF
#define xusb3_buff_2upp_stats0_pfifo_scount_WRITEMASK 0x0
#define xusb3_buff_2upp_stats0_pfifo_scount_VOLATILEMASK 0xFFFF
#define xusb3_buff_2upp_stats0_pfifo_scount_RESETMASK 0xFFFF
#define xusb3_buff_2upp_stats0_pfifo_scount_DEFAULT 0x00000000

#define xusb3_irq0_enable_READMASK 0x1
#define xusb3_irq0_enable_WRITEMASK 0x1
#define xusb3_irq0_enable_VOLATILEMASK 0x0
#define xusb3_irq0_enable_RESETMASK 0x1
#define xusb3_irq0_enable_DEFAULT 0x00000000

#define xusb3_irq0_pending_READMASK 0x1
#define xusb3_irq0_pending_WRITEMASK 0x1
#define xusb3_irq0_pending_VOLATILEMASK 0x1
#define xusb3_irq0_pending_RESETMASK 0x1
#define xusb3_irq0_pending_DEFAULT 0x00000000

#define xusb3_irq0_pending_irq_READMASK 0x1
#define xusb3_irq0_pending_irq_WRITEMASK 0x0
#define xusb3_irq0_pending_irq_VOLATILEMASK 0x0
#define xusb3_irq0_pending_irq_RESETMASK 0x1
#define xusb3_irq0_pending_irq_DEFAULT 0x00000000

#define xusb3_irq0_raw_READMASK 0x1
#define xusb3_irq0_raw_WRITEMASK 0x0
#define xusb3_irq0_raw_VOLATILEMASK 0x1
#define xusb3_irq0_raw_RESETMASK 0x1
#define xusb3_irq0_raw_DEFAULT 0x00000000

#define xusb3_s_SIZE 0x200
#define xusb3_version_SIZE 0x4
#define xusb3_configuration_SIZE 0x4
#define xusb3_control_SIZE 0x4
#define xusb3_rx_partner_fifo_SIZE 0x50
#define xusb3_rx_partner_fifo_version_SIZE 0x4
#define xusb3_rx_partner_fifo_write_engine_SIZE 0x38
#define xusb3_rx_partner_fifo_write_engine_config0_SIZE 0xC
#define xusb3_rx_partner_fifo_write_engine_config0_clear_SIZE 0x4
#define xusb3_rx_partner_fifo_write_engine_config0_mode_SIZE 0x4
#define xusb3_rx_partner_fifo_write_engine_config0_notify_limit_SIZE 0x4
#define xusb3_rx_partner_fifo_write_engine_stats0_SIZE 0x2C
#define xusb3_rx_partner_fifo_write_engine_stats0_rd2clr_config_SIZE 0x4
#define xusb3_rx_partner_fifo_write_engine_stats0_nfifo_dcount_SIZE 0x4
#define xusb3_rx_partner_fifo_write_engine_stats0_pfifo_dcount_SIZE 0x4
#define xusb3_rx_partner_fifo_write_engine_stats0_pkt_max_byte_cnt_err_SIZE 0x4
#define xusb3_rx_partner_fifo_write_engine_stats0_fifo_full_err_SIZE 0x4
#define xusb3_rx_partner_fifo_write_engine_stats0_pkt_err_SIZE 0x4
#define xusb3_rx_partner_fifo_write_engine_stats0_pkt_sop_err_SIZE 0x4
#define xusb3_rx_partner_fifo_write_engine_stats0_wflush_act_SIZE 0x4
#define xusb3_rx_partner_fifo_write_engine_stats0_drp_pkt_rd_SIZE 0x4
#define xusb3_rx_partner_fifo_write_engine_stats0_drp_pkt_wr_SIZE 0x4
#define xusb3_rx_partner_fifo_write_engine_stats0_flow_ctrl_SIZE 0x4
#define xusb3_rx_partner_fifo_read_engine_SIZE 0x14
#define xusb3_rx_partner_fifo_read_engine_config0_SIZE 0x4
#define xusb3_rx_partner_fifo_read_engine_config0_clear_SIZE 0x4
#define xusb3_rx_partner_fifo_read_engine_stats0_SIZE 0x10
#define xusb3_rx_partner_fifo_read_engine_stats0_rd2clr_config_SIZE 0x4
#define xusb3_rx_partner_fifo_read_engine_stats0_rflush_act_SIZE 0x4
#define xusb3_rx_partner_fifo_read_engine_stats0_drp_pkt_SIZE 0x4
#define xusb3_rx_partner_fifo_read_engine_stats0_flow_ctrl_SIZE 0x4
#define xusb3_stats0_SIZE 0x38
#define xusb3_stats0_rd2clr_config_SIZE 0x4
#define xusb3_stats0_link_partner_ptp_violated_SIZE 0x4
#define xusb3_stats0_from_phy_in_sop_SIZE 0x4
#define xusb3_stats0_from_phy_in_eop_SIZE 0x4
#define xusb3_stats0_to_link_out_sop_SIZE 0x4
#define xusb3_stats0_to_link_out_eop_SIZE 0x4
#define xusb3_stats0_from_link_in_sop_SIZE 0x4
#define xusb3_stats0_from_link_in_eop_SIZE 0x4
#define xusb3_stats0_unknown_pkt_drp_SIZE 0x4
#define xusb3_stats0_dwn_stream_busy_drp_SIZE 0x4
#define xusb3_stats0_drop_lone_dpp_SIZE 0x4
#define xusb3_stats0_rcvd_lone_dph_SIZE 0x4
#define xusb3_stats0_timedout_2join_dpp_SIZE 0x4
#define xusb3_stats0_not_rdy_pkt_drp_SIZE 0x4
#define xusb3_ptp_guard_2core_SIZE 0x2C
#define xusb3_ptp_guard_2core_version_SIZE 0x4
#define xusb3_ptp_guard_2core_config0_SIZE 0x8
#define xusb3_ptp_guard_2core_config0_fix_ptp_violations_SIZE 0x4
#define xusb3_ptp_guard_2core_config0_max_cycles_SIZE 0x4
#define xusb3_ptp_guard_2core_stats0_SIZE 0x10
#define xusb3_ptp_guard_2core_stats0_rd2clr_config_SIZE 0x4
#define xusb3_ptp_guard_2core_stats0_missing_sop_err_SIZE 0x4
#define xusb3_ptp_guard_2core_stats0_missing_eop_err_SIZE 0x4
#define xusb3_ptp_guard_2core_stats0_max_cycle_err_SIZE 0x4
#define xusb3_ptp_guard_2core_irq0_SIZE 0x10
#define xusb3_ptp_guard_2core_irq0_enable_SIZE 0x4
#define xusb3_ptp_guard_2core_irq0_pending_SIZE 0x4
#define xusb3_ptp_guard_2core_irq0_pending_irq_SIZE 0x4
#define xusb3_ptp_guard_2core_irq0_raw_SIZE 0x4
#define xusb3_buff_2ulp_SIZE 0x10
#define xusb3_buff_2ulp_control_SIZE 0x4
#define xusb3_buff_2ulp_stats0_SIZE 0xC
#define xusb3_buff_2ulp_stats0_rd2clr_config_SIZE 0x4
#define xusb3_buff_2ulp_stats0_nfifo_dcount_SIZE 0x4
#define xusb3_buff_2ulp_stats0_pfifo_dcount_SIZE 0x4
#define xusb3_buff_2upp_SIZE 0x10
#define xusb3_buff_2upp_control_SIZE 0x4
#define xusb3_buff_2upp_stats0_SIZE 0xC
#define xusb3_buff_2upp_stats0_rd2clr_config_SIZE 0x4
#define xusb3_buff_2upp_stats0_nfifo_scount_SIZE 0x4
#define xusb3_buff_2upp_stats0_pfifo_scount_SIZE 0x4
#define xusb3_irq0_SIZE 0x10
#define xusb3_irq0_enable_SIZE 0x4
#define xusb3_irq0_pending_SIZE 0x4
#define xusb3_irq0_pending_irq_SIZE 0x4
#define xusb3_irq0_raw_SIZE 0x4

#define xusb3_s_OFFSET 0x0
#define xusb3_version_OFFSET 0x0
#define xusb3_configuration_OFFSET 0x4
#define xusb3_control_OFFSET 0x8
#define xusb3_rx_partner_fifo_OFFSET 0xC
#define xusb3_rx_partner_fifo_version_OFFSET 0x0
#define xusb3_rx_partner_fifo_write_engine_OFFSET 0x4
#define xusb3_rx_partner_fifo_write_engine_config0_OFFSET 0x0
#define xusb3_rx_partner_fifo_write_engine_config0_clear_OFFSET 0x0
#define xusb3_rx_partner_fifo_write_engine_config0_mode_OFFSET 0x4
#define xusb3_rx_partner_fifo_write_engine_config0_notify_limit_OFFSET 0x8
#define xusb3_rx_partner_fifo_write_engine_stats0_OFFSET 0xC
#define xusb3_rx_partner_fifo_write_engine_stats0_rd2clr_config_OFFSET 0x0
#define xusb3_rx_partner_fifo_write_engine_stats0_nfifo_dcount_OFFSET 0x4
#define xusb3_rx_partner_fifo_write_engine_stats0_pfifo_dcount_OFFSET 0x8
#define xusb3_rx_partner_fifo_write_engine_stats0_pkt_max_byte_cnt_err_OFFSET 0xC
#define xusb3_rx_partner_fifo_write_engine_stats0_fifo_full_err_OFFSET 0x10
#define xusb3_rx_partner_fifo_write_engine_stats0_pkt_err_OFFSET 0x14
#define xusb3_rx_partner_fifo_write_engine_stats0_pkt_sop_err_OFFSET 0x18
#define xusb3_rx_partner_fifo_write_engine_stats0_wflush_act_OFFSET 0x1C
#define xusb3_rx_partner_fifo_write_engine_stats0_drp_pkt_rd_OFFSET 0x20
#define xusb3_rx_partner_fifo_write_engine_stats0_drp_pkt_wr_OFFSET 0x24
#define xusb3_rx_partner_fifo_write_engine_stats0_flow_ctrl_OFFSET 0x28
#define xusb3_rx_partner_fifo_read_engine_OFFSET 0x3C
#define xusb3_rx_partner_fifo_read_engine_config0_OFFSET 0x0
#define xusb3_rx_partner_fifo_read_engine_config0_clear_OFFSET 0x0
#define xusb3_rx_partner_fifo_read_engine_stats0_OFFSET 0x4
#define xusb3_rx_partner_fifo_read_engine_stats0_rd2clr_config_OFFSET 0x0
#define xusb3_rx_partner_fifo_read_engine_stats0_rflush_act_OFFSET 0x4
#define xusb3_rx_partner_fifo_read_engine_stats0_drp_pkt_OFFSET 0x8
#define xusb3_rx_partner_fifo_read_engine_stats0_flow_ctrl_OFFSET 0xC
#define xusb3_stats0_OFFSET 0x5C
#define xusb3_stats0_rd2clr_config_OFFSET 0x0
#define xusb3_stats0_link_partner_ptp_violated_OFFSET 0x4
#define xusb3_stats0_from_phy_in_sop_OFFSET 0x8
#define xusb3_stats0_from_phy_in_eop_OFFSET 0xC
#define xusb3_stats0_to_link_out_sop_OFFSET 0x10
#define xusb3_stats0_to_link_out_eop_OFFSET 0x14
#define xusb3_stats0_from_link_in_sop_OFFSET 0x18
#define xusb3_stats0_from_link_in_eop_OFFSET 0x1C
#define xusb3_stats0_unknown_pkt_drp_OFFSET 0x20
#define xusb3_stats0_dwn_stream_busy_drp_OFFSET 0x24
#define xusb3_stats0_drop_lone_dpp_OFFSET 0x28
#define xusb3_stats0_rcvd_lone_dph_OFFSET 0x2C
#define xusb3_stats0_timedout_2join_dpp_OFFSET 0x30
#define xusb3_stats0_not_rdy_pkt_drp_OFFSET 0x34
#define xusb3_ptp_guard_2core_OFFSET 0x94
#define xusb3_ptp_guard_2core_version_OFFSET 0x0
#define xusb3_ptp_guard_2core_config0_OFFSET 0x4
#define xusb3_ptp_guard_2core_config0_fix_ptp_violations_OFFSET 0x0
#define xusb3_ptp_guard_2core_config0_max_cycles_OFFSET 0x4
#define xusb3_ptp_guard_2core_stats0_OFFSET 0xC
#define xusb3_ptp_guard_2core_stats0_rd2clr_config_OFFSET 0x0
#define xusb3_ptp_guard_2core_stats0_missing_sop_err_OFFSET 0x4
#define xusb3_ptp_guard_2core_stats0_missing_eop_err_OFFSET 0x8
#define xusb3_ptp_guard_2core_stats0_max_cycle_err_OFFSET 0xC
#define xusb3_ptp_guard_2core_irq0_OFFSET 0x1C
#define xusb3_ptp_guard_2core_irq0_enable_OFFSET 0x0
#define xusb3_ptp_guard_2core_irq0_pending_OFFSET 0x4
#define xusb3_ptp_guard_2core_irq0_pending_irq_OFFSET 0x8
#define xusb3_ptp_guard_2core_irq0_raw_OFFSET 0xC
#define xusb3_buff_2ulp_OFFSET 0xC0
#define xusb3_buff_2ulp_control_OFFSET 0x0
#define xusb3_buff_2ulp_stats0_OFFSET 0x4
#define xusb3_buff_2ulp_stats0_rd2clr_config_OFFSET 0x0
#define xusb3_buff_2ulp_stats0_nfifo_dcount_OFFSET 0x4
#define xusb3_buff_2ulp_stats0_pfifo_dcount_OFFSET 0x8
#define xusb3_buff_2upp_OFFSET 0xD0
#define xusb3_buff_2upp_control_OFFSET 0x0
#define xusb3_buff_2upp_stats0_OFFSET 0x4
#define xusb3_buff_2upp_stats0_rd2clr_config_OFFSET 0x0
#define xusb3_buff_2upp_stats0_nfifo_scount_OFFSET 0x4
#define xusb3_buff_2upp_stats0_pfifo_scount_OFFSET 0x8
#define xusb3_irq0_OFFSET 0xE0
#define xusb3_irq0_enable_OFFSET 0x0
#define xusb3_irq0_pending_OFFSET 0x4
#define xusb3_irq0_pending_irq_OFFSET 0x8
#define xusb3_irq0_raw_OFFSET 0xC

#define xusb3_s_ADDRESS 0x000
#define xusb3_version_ADDRESS 0x000
#define xusb3_configuration_ADDRESS 0x004
#define xusb3_control_ADDRESS 0x008
#define xusb3_rx_partner_fifo_ADDRESS 0x00C
#define xusb3_rx_partner_fifo_version_ADDRESS 0x00C
#define xusb3_rx_partner_fifo_write_engine_ADDRESS 0x010
#define xusb3_rx_partner_fifo_write_engine_config0_ADDRESS 0x010
#define xusb3_rx_partner_fifo_write_engine_config0_clear_ADDRESS 0x010
#define xusb3_rx_partner_fifo_write_engine_config0_mode_ADDRESS 0x014
#define xusb3_rx_partner_fifo_write_engine_config0_notify_limit_ADDRESS 0x018
#define xusb3_rx_partner_fifo_write_engine_stats0_ADDRESS 0x01C
#define xusb3_rx_partner_fifo_write_engine_stats0_rd2clr_config_ADDRESS 0x01C
#define xusb3_rx_partner_fifo_write_engine_stats0_nfifo_dcount_ADDRESS 0x020
#define xusb3_rx_partner_fifo_write_engine_stats0_pfifo_dcount_ADDRESS 0x024
#define xusb3_rx_partner_fifo_write_engine_stats0_pkt_max_byte_cnt_err_ADDRESS 0x028
#define xusb3_rx_partner_fifo_write_engine_stats0_fifo_full_err_ADDRESS 0x02C
#define xusb3_rx_partner_fifo_write_engine_stats0_pkt_err_ADDRESS 0x030
#define xusb3_rx_partner_fifo_write_engine_stats0_pkt_sop_err_ADDRESS 0x034
#define xusb3_rx_partner_fifo_write_engine_stats0_wflush_act_ADDRESS 0x038
#define xusb3_rx_partner_fifo_write_engine_stats0_drp_pkt_rd_ADDRESS 0x03C
#define xusb3_rx_partner_fifo_write_engine_stats0_drp_pkt_wr_ADDRESS 0x040
#define xusb3_rx_partner_fifo_write_engine_stats0_flow_ctrl_ADDRESS 0x044
#define xusb3_rx_partner_fifo_read_engine_ADDRESS 0x048
#define xusb3_rx_partner_fifo_read_engine_config0_ADDRESS 0x048
#define xusb3_rx_partner_fifo_read_engine_config0_clear_ADDRESS 0x048
#define xusb3_rx_partner_fifo_read_engine_stats0_ADDRESS 0x04C
#define xusb3_rx_partner_fifo_read_engine_stats0_rd2clr_config_ADDRESS 0x04C
#define xusb3_rx_partner_fifo_read_engine_stats0_rflush_act_ADDRESS 0x050
#define xusb3_rx_partner_fifo_read_engine_stats0_drp_pkt_ADDRESS 0x054
#define xusb3_rx_partner_fifo_read_engine_stats0_flow_ctrl_ADDRESS 0x058
#define xusb3_stats0_ADDRESS 0x05C
#define xusb3_stats0_rd2clr_config_ADDRESS 0x05C
#define xusb3_stats0_link_partner_ptp_violated_ADDRESS 0x060
#define xusb3_stats0_from_phy_in_sop_ADDRESS 0x064
#define xusb3_stats0_from_phy_in_eop_ADDRESS 0x068
#define xusb3_stats0_to_link_out_sop_ADDRESS 0x06C
#define xusb3_stats0_to_link_out_eop_ADDRESS 0x070
#define xusb3_stats0_from_link_in_sop_ADDRESS 0x074
#define xusb3_stats0_from_link_in_eop_ADDRESS 0x078
#define xusb3_stats0_unknown_pkt_drp_ADDRESS 0x07C
#define xusb3_stats0_dwn_stream_busy_drp_ADDRESS 0x080
#define xusb3_stats0_drop_lone_dpp_ADDRESS 0x084
#define xusb3_stats0_rcvd_lone_dph_ADDRESS 0x088
#define xusb3_stats0_timedout_2join_dpp_ADDRESS 0x08C
#define xusb3_stats0_not_rdy_pkt_drp_ADDRESS 0x090
#define xusb3_ptp_guard_2core_ADDRESS 0x094
#define xusb3_ptp_guard_2core_version_ADDRESS 0x094
#define xusb3_ptp_guard_2core_config0_ADDRESS 0x098
#define xusb3_ptp_guard_2core_config0_fix_ptp_violations_ADDRESS 0x098
#define xusb3_ptp_guard_2core_config0_max_cycles_ADDRESS 0x09C
#define xusb3_ptp_guard_2core_stats0_ADDRESS 0x0A0
#define xusb3_ptp_guard_2core_stats0_rd2clr_config_ADDRESS 0x0A0
#define xusb3_ptp_guard_2core_stats0_missing_sop_err_ADDRESS 0x0A4
#define xusb3_ptp_guard_2core_stats0_missing_eop_err_ADDRESS 0x0A8
#define xusb3_ptp_guard_2core_stats0_max_cycle_err_ADDRESS 0x0AC
#define xusb3_ptp_guard_2core_irq0_ADDRESS 0x0B0
#define xusb3_ptp_guard_2core_irq0_enable_ADDRESS 0x0B0
#define xusb3_ptp_guard_2core_irq0_pending_ADDRESS 0x0B4
#define xusb3_ptp_guard_2core_irq0_pending_irq_ADDRESS 0x0B8
#define xusb3_ptp_guard_2core_irq0_raw_ADDRESS 0x0BC
#define xusb3_buff_2ulp_ADDRESS 0x0C0
#define xusb3_buff_2ulp_control_ADDRESS 0x0C0
#define xusb3_buff_2ulp_stats0_ADDRESS 0x0C4
#define xusb3_buff_2ulp_stats0_rd2clr_config_ADDRESS 0x0C4
#define xusb3_buff_2ulp_stats0_nfifo_dcount_ADDRESS 0x0C8
#define xusb3_buff_2ulp_stats0_pfifo_dcount_ADDRESS 0x0CC
#define xusb3_buff_2upp_ADDRESS 0x0D0
#define xusb3_buff_2upp_control_ADDRESS 0x0D0
#define xusb3_buff_2upp_stats0_ADDRESS 0x0D4
#define xusb3_buff_2upp_stats0_rd2clr_config_ADDRESS 0x0D4
#define xusb3_buff_2upp_stats0_nfifo_scount_ADDRESS 0x0D8
#define xusb3_buff_2upp_stats0_pfifo_scount_ADDRESS 0x0DC
#define xusb3_irq0_ADDRESS 0x0E0
#define xusb3_irq0_enable_ADDRESS 0x0E0
#define xusb3_irq0_pending_ADDRESS 0x0E4
#define xusb3_irq0_pending_irq_ADDRESS 0x0E8
#define xusb3_irq0_raw_ADDRESS 0x0EC
#define XUSB3_VERSION_MAJOR_OFFSET 16
#define XUSB3_VERSION_MAJOR_MASK 0xFF0000
#define XUSB3_VERSION_MINOR_OFFSET 8
#define XUSB3_VERSION_MINOR_MASK 0xFF00
#define XUSB3_VERSION_PATCH_OFFSET 0
#define XUSB3_VERSION_PATCH_MASK 0xFF
#define XUSB3_CONFIGURATION_RX_BUFF_NEAR_FULL_LIMIT_OFFSET 22
#define XUSB3_CONFIGURATION_RX_BUFF_NEAR_FULL_LIMIT_MASK 0x3FC00000
#define XUSB3_CONFIGURATION_UPP_BYPASS_OFFSET 21
#define XUSB3_CONFIGURATION_UPP_BYPASS_MASK 0x200000
#define XUSB3_CONFIGURATION_UPP_BYPASS 0x200000
#define XUSB3_CONFIGURATION_UPP_IS_PRESENT_OFFSET 20
#define XUSB3_CONFIGURATION_UPP_IS_PRESENT_MASK 0x100000
#define XUSB3_CONFIGURATION_UPP_IS_PRESENT 0x100000
#define XUSB3_CONFIGURATION_SPLIT_DP_WAIT_TIME_OFFSET 4
#define XUSB3_CONFIGURATION_SPLIT_DP_WAIT_TIME_MASK 0xFFFF0
#define XUSB3_CONFIGURATION_SPLIT_DP_MODE_OFFSET 3
#define XUSB3_CONFIGURATION_SPLIT_DP_MODE_MASK 0x8
#define XUSB3_CONFIGURATION_SPLIT_DP_MODE 0x8
#define XUSB3_CONFIGURATION_ALLOW_RX_BUFF_FILL_OFFSET 2
#define XUSB3_CONFIGURATION_ALLOW_RX_BUFF_FILL_MASK 0x4
#define XUSB3_CONFIGURATION_ALLOW_RX_BUFF_FILL 0x4
#define XUSB3_CONFIGURATION_DROP_ITP_PKTS_OFFSET 1
#define XUSB3_CONFIGURATION_DROP_ITP_PKTS_MASK 0x2
#define XUSB3_CONFIGURATION_DROP_ITP_PKTS 0x2
#define XUSB3_CONFIGURATION_UPSTREAM_PORT_OFFSET 0
#define XUSB3_CONFIGURATION_UPSTREAM_PORT_MASK 0x1
#define XUSB3_CONFIGURATION_UPSTREAM_PORT 0x1
#define XUSB3_CONTROL_REMOVE_CRDTS_OFFSET 0
#define XUSB3_CONTROL_REMOVE_CRDTS_MASK 0x1
#define XUSB3_CONTROL_REMOVE_CRDTS 0x1
#define XUSB3_RX_PARTNER_FIFO_VERSION_MAJOR_OFFSET 16
#define XUSB3_RX_PARTNER_FIFO_VERSION_MAJOR_MASK 0xFF0000
#define XUSB3_RX_PARTNER_FIFO_VERSION_MINOR_OFFSET 8
#define XUSB3_RX_PARTNER_FIFO_VERSION_MINOR_MASK 0xFF00
#define XUSB3_RX_PARTNER_FIFO_VERSION_PATCH_OFFSET 0
#define XUSB3_RX_PARTNER_FIFO_VERSION_PATCH_MASK 0xFF
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_CONFIG0_CLEAR_WCLR_OFFSET 0
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_CONFIG0_CLEAR_WCLR_MASK 0x1
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_CONFIG0_CLEAR_WCLR 0x1
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_CONFIG0_MODE_DRP_ON_SOP_OFFSET 3
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_CONFIG0_MODE_DRP_ON_SOP_MASK 0x8
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_CONFIG0_MODE_DRP_ON_SOP 0x8
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_CONFIG0_MODE_DRP_ON_PKT_ERR_OFFSET 2
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_CONFIG0_MODE_DRP_ON_PKT_ERR_MASK 0x4
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_CONFIG0_MODE_DRP_ON_PKT_ERR 0x4
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_CONFIG0_MODE_PKT_STRM_OFFSET 1
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_CONFIG0_MODE_PKT_STRM_MASK 0x2
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_CONFIG0_MODE_PKT_STRM 0x2
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_CONFIG0_MODE_FLW_CTRL_EN_OFFSET 0
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_CONFIG0_MODE_FLW_CTRL_EN_MASK 0x1
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_CONFIG0_MODE_FLW_CTRL_EN 0x1
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_CONFIG0_NOTIFY_LIMIT_NTFY_LMT_OFFSET 0
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_CONFIG0_NOTIFY_LIMIT_NTFY_LMT_MASK 0xFFFFFFFF
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_RD2CLR_CONFIG_FLOW_CTRL_OFFSET 9
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_RD2CLR_CONFIG_FLOW_CTRL_MASK 0x200
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_RD2CLR_CONFIG_FLOW_CTRL 0x200
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_RD2CLR_CONFIG_DRP_PKT_WR_OFFSET 8
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_RD2CLR_CONFIG_DRP_PKT_WR_MASK 0x100
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_RD2CLR_CONFIG_DRP_PKT_WR 0x100
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_RD2CLR_CONFIG_DRP_PKT_RD_OFFSET 7
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_RD2CLR_CONFIG_DRP_PKT_RD_MASK 0x80
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_RD2CLR_CONFIG_DRP_PKT_RD 0x80
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_RD2CLR_CONFIG_WFLUSH_ACT_OFFSET 6
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_RD2CLR_CONFIG_WFLUSH_ACT_MASK 0x40
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_RD2CLR_CONFIG_WFLUSH_ACT 0x40
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_RD2CLR_CONFIG_PKT_SOP_ERR_OFFSET 5
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_RD2CLR_CONFIG_PKT_SOP_ERR_MASK 0x20
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_RD2CLR_CONFIG_PKT_SOP_ERR 0x20
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_RD2CLR_CONFIG_PKT_ERR_OFFSET 4
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_RD2CLR_CONFIG_PKT_ERR_MASK 0x10
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_RD2CLR_CONFIG_PKT_ERR 0x10
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_RD2CLR_CONFIG_FIFO_FULL_ERR_OFFSET 3
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_RD2CLR_CONFIG_FIFO_FULL_ERR_MASK 0x8
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_RD2CLR_CONFIG_FIFO_FULL_ERR 0x8
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_RD2CLR_CONFIG_PKT_MAX_BYTE_CNT_ERR_OFFSET 2
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_RD2CLR_CONFIG_PKT_MAX_BYTE_CNT_ERR_MASK 0x4
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_RD2CLR_CONFIG_PKT_MAX_BYTE_CNT_ERR 0x4
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_RD2CLR_CONFIG_PFIFO_DCOUNT_OFFSET 1
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_RD2CLR_CONFIG_PFIFO_DCOUNT_MASK 0x2
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_RD2CLR_CONFIG_PFIFO_DCOUNT 0x2
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_RD2CLR_CONFIG_NFIFO_DCOUNT_OFFSET 0
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_RD2CLR_CONFIG_NFIFO_DCOUNT_MASK 0x1
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_RD2CLR_CONFIG_NFIFO_DCOUNT 0x1
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_NFIFO_DCOUNT_NFIFO_DCOUNT_OFFSET 0
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_NFIFO_DCOUNT_NFIFO_DCOUNT_MASK 0xFFFF
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_PFIFO_DCOUNT_PFIFO_DCOUNT_OFFSET 0
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_PFIFO_DCOUNT_PFIFO_DCOUNT_MASK 0xFFFF
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_PKT_MAX_BYTE_CNT_ERR_PKT_MAX_BYTE_CNT_ERR_OFFSET 0
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_PKT_MAX_BYTE_CNT_ERR_PKT_MAX_BYTE_CNT_ERR_MASK 0xFF
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_FIFO_FULL_ERR_FIFO_FULL_ERR_OFFSET 0
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_FIFO_FULL_ERR_FIFO_FULL_ERR_MASK 0xFF
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_PKT_ERR_PKT_ERR_OFFSET 0
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_PKT_ERR_PKT_ERR_MASK 0xFF
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_PKT_SOP_ERR_PKT_SOP_ERR_OFFSET 0
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_PKT_SOP_ERR_PKT_SOP_ERR_MASK 0xFF
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_WFLUSH_ACT_WFLUSH_ACT_OFFSET 0
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_WFLUSH_ACT_WFLUSH_ACT_MASK 0xFF
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_DRP_PKT_RD_DRP_PKT_RD_OFFSET 0
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_DRP_PKT_RD_DRP_PKT_RD_MASK 0xFF
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_DRP_PKT_WR_DRP_PKT_WR_OFFSET 0
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_DRP_PKT_WR_DRP_PKT_WR_MASK 0xFF
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_FLOW_CTRL_FLOW_CTRL_OFFSET 0
#define XUSB3_RX_PARTNER_FIFO_WRITE_ENGINE_STATS0_FLOW_CTRL_FLOW_CTRL_MASK 0xFFFF
#define XUSB3_RX_PARTNER_FIFO_READ_ENGINE_CONFIG0_CLEAR_RCLR_OFFSET 0
#define XUSB3_RX_PARTNER_FIFO_READ_ENGINE_CONFIG0_CLEAR_RCLR_MASK 0x1
#define XUSB3_RX_PARTNER_FIFO_READ_ENGINE_CONFIG0_CLEAR_RCLR 0x1
#define XUSB3_RX_PARTNER_FIFO_READ_ENGINE_STATS0_RD2CLR_CONFIG_FLOW_CTRL_OFFSET 2
#define XUSB3_RX_PARTNER_FIFO_READ_ENGINE_STATS0_RD2CLR_CONFIG_FLOW_CTRL_MASK 0x4
#define XUSB3_RX_PARTNER_FIFO_READ_ENGINE_STATS0_RD2CLR_CONFIG_FLOW_CTRL 0x4
#define XUSB3_RX_PARTNER_FIFO_READ_ENGINE_STATS0_RD2CLR_CONFIG_DRP_PKT_OFFSET 1
#define XUSB3_RX_PARTNER_FIFO_READ_ENGINE_STATS0_RD2CLR_CONFIG_DRP_PKT_MASK 0x2
#define XUSB3_RX_PARTNER_FIFO_READ_ENGINE_STATS0_RD2CLR_CONFIG_DRP_PKT 0x2
#define XUSB3_RX_PARTNER_FIFO_READ_ENGINE_STATS0_RD2CLR_CONFIG_RFLUSH_ACT_OFFSET 0
#define XUSB3_RX_PARTNER_FIFO_READ_ENGINE_STATS0_RD2CLR_CONFIG_RFLUSH_ACT_MASK 0x1
#define XUSB3_RX_PARTNER_FIFO_READ_ENGINE_STATS0_RD2CLR_CONFIG_RFLUSH_ACT 0x1
#define XUSB3_RX_PARTNER_FIFO_READ_ENGINE_STATS0_RFLUSH_ACT_RFLUSH_ACT_OFFSET 0
#define XUSB3_RX_PARTNER_FIFO_READ_ENGINE_STATS0_RFLUSH_ACT_RFLUSH_ACT_MASK 0xFF
#define XUSB3_RX_PARTNER_FIFO_READ_ENGINE_STATS0_DRP_PKT_DRP_PKT_OFFSET 0
#define XUSB3_RX_PARTNER_FIFO_READ_ENGINE_STATS0_DRP_PKT_DRP_PKT_MASK 0xFF
#define XUSB3_RX_PARTNER_FIFO_READ_ENGINE_STATS0_FLOW_CTRL_FLOW_CTRL_OFFSET 0
#define XUSB3_RX_PARTNER_FIFO_READ_ENGINE_STATS0_FLOW_CTRL_FLOW_CTRL_MASK 0xFFFF
#define XUSB3_STATS0_RD2CLR_CONFIG_NOT_RDY_PKT_DRP_OFFSET 12
#define XUSB3_STATS0_RD2CLR_CONFIG_NOT_RDY_PKT_DRP_MASK 0x1000
#define XUSB3_STATS0_RD2CLR_CONFIG_NOT_RDY_PKT_DRP 0x1000
#define XUSB3_STATS0_RD2CLR_CONFIG_TIMEDOUT_2JOIN_DPP_OFFSET 11
#define XUSB3_STATS0_RD2CLR_CONFIG_TIMEDOUT_2JOIN_DPP_MASK 0x800
#define XUSB3_STATS0_RD2CLR_CONFIG_TIMEDOUT_2JOIN_DPP 0x800
#define XUSB3_STATS0_RD2CLR_CONFIG_RCVD_LONE_DPH_OFFSET 10
#define XUSB3_STATS0_RD2CLR_CONFIG_RCVD_LONE_DPH_MASK 0x400
#define XUSB3_STATS0_RD2CLR_CONFIG_RCVD_LONE_DPH 0x400
#define XUSB3_STATS0_RD2CLR_CONFIG_DROP_LONE_DPP_OFFSET 9
#define XUSB3_STATS0_RD2CLR_CONFIG_DROP_LONE_DPP_MASK 0x200
#define XUSB3_STATS0_RD2CLR_CONFIG_DROP_LONE_DPP 0x200
#define XUSB3_STATS0_RD2CLR_CONFIG_DWN_STREAM_BUSY_DRP_OFFSET 8
#define XUSB3_STATS0_RD2CLR_CONFIG_DWN_STREAM_BUSY_DRP_MASK 0x100
#define XUSB3_STATS0_RD2CLR_CONFIG_DWN_STREAM_BUSY_DRP 0x100
#define XUSB3_STATS0_RD2CLR_CONFIG_UNKNOWN_PKT_DRP_OFFSET 7
#define XUSB3_STATS0_RD2CLR_CONFIG_UNKNOWN_PKT_DRP_MASK 0x80
#define XUSB3_STATS0_RD2CLR_CONFIG_UNKNOWN_PKT_DRP 0x80
#define XUSB3_STATS0_RD2CLR_CONFIG_FROM_LINK_IN_EOP_OFFSET 6
#define XUSB3_STATS0_RD2CLR_CONFIG_FROM_LINK_IN_EOP_MASK 0x40
#define XUSB3_STATS0_RD2CLR_CONFIG_FROM_LINK_IN_EOP 0x40
#define XUSB3_STATS0_RD2CLR_CONFIG_FROM_LINK_IN_SOP_OFFSET 5
#define XUSB3_STATS0_RD2CLR_CONFIG_FROM_LINK_IN_SOP_MASK 0x20
#define XUSB3_STATS0_RD2CLR_CONFIG_FROM_LINK_IN_SOP 0x20
#define XUSB3_STATS0_RD2CLR_CONFIG_TO_LINK_OUT_EOP_OFFSET 4
#define XUSB3_STATS0_RD2CLR_CONFIG_TO_LINK_OUT_EOP_MASK 0x10
#define XUSB3_STATS0_RD2CLR_CONFIG_TO_LINK_OUT_EOP 0x10
#define XUSB3_STATS0_RD2CLR_CONFIG_TO_LINK_OUT_SOP_OFFSET 3
#define XUSB3_STATS0_RD2CLR_CONFIG_TO_LINK_OUT_SOP_MASK 0x8
#define XUSB3_STATS0_RD2CLR_CONFIG_TO_LINK_OUT_SOP 0x8
#define XUSB3_STATS0_RD2CLR_CONFIG_FROM_PHY_IN_EOP_OFFSET 2
#define XUSB3_STATS0_RD2CLR_CONFIG_FROM_PHY_IN_EOP_MASK 0x4
#define XUSB3_STATS0_RD2CLR_CONFIG_FROM_PHY_IN_EOP 0x4
#define XUSB3_STATS0_RD2CLR_CONFIG_FROM_PHY_IN_SOP_OFFSET 1
#define XUSB3_STATS0_RD2CLR_CONFIG_FROM_PHY_IN_SOP_MASK 0x2
#define XUSB3_STATS0_RD2CLR_CONFIG_FROM_PHY_IN_SOP 0x2
#define XUSB3_STATS0_RD2CLR_CONFIG_LINK_PARTNER_PTP_VIOLATED_OFFSET 0
#define XUSB3_STATS0_RD2CLR_CONFIG_LINK_PARTNER_PTP_VIOLATED_MASK 0x1
#define XUSB3_STATS0_RD2CLR_CONFIG_LINK_PARTNER_PTP_VIOLATED 0x1
#define XUSB3_STATS0_LINK_PARTNER_PTP_VIOLATED_LINK_PARTNER_PTP_VIOLATED_OFFSET 0
#define XUSB3_STATS0_LINK_PARTNER_PTP_VIOLATED_LINK_PARTNER_PTP_VIOLATED_MASK 0xFF
#define XUSB3_STATS0_FROM_PHY_IN_SOP_FROM_PHY_IN_SOP_OFFSET 0
#define XUSB3_STATS0_FROM_PHY_IN_SOP_FROM_PHY_IN_SOP_MASK 0xFFFFFFFF
#define XUSB3_STATS0_FROM_PHY_IN_EOP_FROM_PHY_IN_EOP_OFFSET 0
#define XUSB3_STATS0_FROM_PHY_IN_EOP_FROM_PHY_IN_EOP_MASK 0xFFFFFFFF
#define XUSB3_STATS0_TO_LINK_OUT_SOP_TO_LINK_OUT_SOP_OFFSET 0
#define XUSB3_STATS0_TO_LINK_OUT_SOP_TO_LINK_OUT_SOP_MASK 0xFFFFFFFF
#define XUSB3_STATS0_TO_LINK_OUT_EOP_TO_LINK_OUT_EOP_OFFSET 0
#define XUSB3_STATS0_TO_LINK_OUT_EOP_TO_LINK_OUT_EOP_MASK 0xFFFFFFFF
#define XUSB3_STATS0_FROM_LINK_IN_SOP_FROM_LINK_IN_SOP_OFFSET 0
#define XUSB3_STATS0_FROM_LINK_IN_SOP_FROM_LINK_IN_SOP_MASK 0xFFFFFFFF
#define XUSB3_STATS0_FROM_LINK_IN_EOP_FROM_LINK_IN_EOP_OFFSET 0
#define XUSB3_STATS0_FROM_LINK_IN_EOP_FROM_LINK_IN_EOP_MASK 0xFFFFFFFF
#define XUSB3_STATS0_UNKNOWN_PKT_DRP_UNKNOWN_PKT_DRP_OFFSET 0
#define XUSB3_STATS0_UNKNOWN_PKT_DRP_UNKNOWN_PKT_DRP_MASK 0xFFFF
#define XUSB3_STATS0_DWN_STREAM_BUSY_DRP_DWN_STREAM_BUSY_DRP_OFFSET 0
#define XUSB3_STATS0_DWN_STREAM_BUSY_DRP_DWN_STREAM_BUSY_DRP_MASK 0xFFFF
#define XUSB3_STATS0_DROP_LONE_DPP_DROP_LONE_DPP_OFFSET 0
#define XUSB3_STATS0_DROP_LONE_DPP_DROP_LONE_DPP_MASK 0xFFFF
#define XUSB3_STATS0_RCVD_LONE_DPH_RCVD_LONE_DPH_OFFSET 0
#define XUSB3_STATS0_RCVD_LONE_DPH_RCVD_LONE_DPH_MASK 0xFFFF
#define XUSB3_STATS0_TIMEDOUT_2JOIN_DPP_TIMEDOUT_2JOIN_DPP_OFFSET 0
#define XUSB3_STATS0_TIMEDOUT_2JOIN_DPP_TIMEDOUT_2JOIN_DPP_MASK 0xFFFF
#define XUSB3_STATS0_NOT_RDY_PKT_DRP_NOT_RDY_PKT_DRP_OFFSET 0
#define XUSB3_STATS0_NOT_RDY_PKT_DRP_NOT_RDY_PKT_DRP_MASK 0xFFFF
#define XUSB3_PTP_GUARD_2CORE_VERSION_MAJOR_OFFSET 16
#define XUSB3_PTP_GUARD_2CORE_VERSION_MAJOR_MASK 0xFF0000
#define XUSB3_PTP_GUARD_2CORE_VERSION_MINOR_OFFSET 8
#define XUSB3_PTP_GUARD_2CORE_VERSION_MINOR_MASK 0xFF00
#define XUSB3_PTP_GUARD_2CORE_VERSION_PATCH_OFFSET 0
#define XUSB3_PTP_GUARD_2CORE_VERSION_PATCH_MASK 0xFF
#define XUSB3_PTP_GUARD_2CORE_CONFIG0_FIX_PTP_VIOLATIONS_IMPLEMENTED_OFFSET 1
#define XUSB3_PTP_GUARD_2CORE_CONFIG0_FIX_PTP_VIOLATIONS_IMPLEMENTED_MASK 0x2
#define XUSB3_PTP_GUARD_2CORE_CONFIG0_FIX_PTP_VIOLATIONS_IMPLEMENTED 0x2
#define XUSB3_PTP_GUARD_2CORE_CONFIG0_FIX_PTP_VIOLATIONS_ACTIVATE_OFFSET 0
#define XUSB3_PTP_GUARD_2CORE_CONFIG0_FIX_PTP_VIOLATIONS_ACTIVATE_MASK 0x1
#define XUSB3_PTP_GUARD_2CORE_CONFIG0_FIX_PTP_VIOLATIONS_ACTIVATE 0x1
#define XUSB3_PTP_GUARD_2CORE_CONFIG0_MAX_CYCLES_MAX_CYCLE_MODE_OFFSET 16
#define XUSB3_PTP_GUARD_2CORE_CONFIG0_MAX_CYCLES_MAX_CYCLE_MODE_MASK 0xF0000
#define XUSB3_PTP_GUARD_2CORE_CONFIG0_MAX_CYCLES_MAX_CYCLES_OFFSET 0
#define XUSB3_PTP_GUARD_2CORE_CONFIG0_MAX_CYCLES_MAX_CYCLES_MASK 0xFFFF
#define XUSB3_PTP_GUARD_2CORE_STATS0_RD2CLR_CONFIG_MAX_CYCLE_ERR_OFFSET 2
#define XUSB3_PTP_GUARD_2CORE_STATS0_RD2CLR_CONFIG_MAX_CYCLE_ERR_MASK 0x4
#define XUSB3_PTP_GUARD_2CORE_STATS0_RD2CLR_CONFIG_MAX_CYCLE_ERR 0x4
#define XUSB3_PTP_GUARD_2CORE_STATS0_RD2CLR_CONFIG_MISSING_EOP_ERR_OFFSET 1
#define XUSB3_PTP_GUARD_2CORE_STATS0_RD2CLR_CONFIG_MISSING_EOP_ERR_MASK 0x2
#define XUSB3_PTP_GUARD_2CORE_STATS0_RD2CLR_CONFIG_MISSING_EOP_ERR 0x2
#define XUSB3_PTP_GUARD_2CORE_STATS0_RD2CLR_CONFIG_MISSING_SOP_ERR_OFFSET 0
#define XUSB3_PTP_GUARD_2CORE_STATS0_RD2CLR_CONFIG_MISSING_SOP_ERR_MASK 0x1
#define XUSB3_PTP_GUARD_2CORE_STATS0_RD2CLR_CONFIG_MISSING_SOP_ERR 0x1
#define XUSB3_PTP_GUARD_2CORE_STATS0_MISSING_SOP_ERR_MISSING_SOP_ERR_OFFSET 0
#define XUSB3_PTP_GUARD_2CORE_STATS0_MISSING_SOP_ERR_MISSING_SOP_ERR_MASK 0xFFFF
#define XUSB3_PTP_GUARD_2CORE_STATS0_MISSING_EOP_ERR_MISSING_EOP_ERR_OFFSET 0
#define XUSB3_PTP_GUARD_2CORE_STATS0_MISSING_EOP_ERR_MISSING_EOP_ERR_MASK 0xFFFF
#define XUSB3_PTP_GUARD_2CORE_STATS0_MAX_CYCLE_ERR_MAX_CYCLE_ERR_OFFSET 0
#define XUSB3_PTP_GUARD_2CORE_STATS0_MAX_CYCLE_ERR_MAX_CYCLE_ERR_MASK 0xFFFF
#define XUSB3_PTP_GUARD_2CORE_IRQ0_ENABLE_MAX_CYCLE_ERR_OFFSET 2
#define XUSB3_PTP_GUARD_2CORE_IRQ0_ENABLE_MAX_CYCLE_ERR_MASK 0x4
#define XUSB3_PTP_GUARD_2CORE_IRQ0_ENABLE_MAX_CYCLE_ERR 0x4
#define XUSB3_PTP_GUARD_2CORE_IRQ0_ENABLE_MISSING_EOP_ERR_OFFSET 1
#define XUSB3_PTP_GUARD_2CORE_IRQ0_ENABLE_MISSING_EOP_ERR_MASK 0x2
#define XUSB3_PTP_GUARD_2CORE_IRQ0_ENABLE_MISSING_EOP_ERR 0x2
#define XUSB3_PTP_GUARD_2CORE_IRQ0_ENABLE_MISSING_SOP_ERR_OFFSET 0
#define XUSB3_PTP_GUARD_2CORE_IRQ0_ENABLE_MISSING_SOP_ERR_MASK 0x1
#define XUSB3_PTP_GUARD_2CORE_IRQ0_ENABLE_MISSING_SOP_ERR 0x1
#define XUSB3_PTP_GUARD_2CORE_IRQ0_PENDING_MAX_CYCLE_ERR_OFFSET 2
#define XUSB3_PTP_GUARD_2CORE_IRQ0_PENDING_MAX_CYCLE_ERR_MASK 0x4
#define XUSB3_PTP_GUARD_2CORE_IRQ0_PENDING_MAX_CYCLE_ERR 0x4
#define XUSB3_PTP_GUARD_2CORE_IRQ0_PENDING_MISSING_EOP_ERR_OFFSET 1
#define XUSB3_PTP_GUARD_2CORE_IRQ0_PENDING_MISSING_EOP_ERR_MASK 0x2
#define XUSB3_PTP_GUARD_2CORE_IRQ0_PENDING_MISSING_EOP_ERR 0x2
#define XUSB3_PTP_GUARD_2CORE_IRQ0_PENDING_MISSING_SOP_ERR_OFFSET 0
#define XUSB3_PTP_GUARD_2CORE_IRQ0_PENDING_MISSING_SOP_ERR_MASK 0x1
#define XUSB3_PTP_GUARD_2CORE_IRQ0_PENDING_MISSING_SOP_ERR 0x1
#define XUSB3_PTP_GUARD_2CORE_IRQ0_PENDING_IRQ_MAX_CYCLE_ERR_OFFSET 2
#define XUSB3_PTP_GUARD_2CORE_IRQ0_PENDING_IRQ_MAX_CYCLE_ERR_MASK 0x4
#define XUSB3_PTP_GUARD_2CORE_IRQ0_PENDING_IRQ_MAX_CYCLE_ERR 0x4
#define XUSB3_PTP_GUARD_2CORE_IRQ0_PENDING_IRQ_MISSING_EOP_ERR_OFFSET 1
#define XUSB3_PTP_GUARD_2CORE_IRQ0_PENDING_IRQ_MISSING_EOP_ERR_MASK 0x2
#define XUSB3_PTP_GUARD_2CORE_IRQ0_PENDING_IRQ_MISSING_EOP_ERR 0x2
#define XUSB3_PTP_GUARD_2CORE_IRQ0_PENDING_IRQ_MISSING_SOP_ERR_OFFSET 0
#define XUSB3_PTP_GUARD_2CORE_IRQ0_PENDING_IRQ_MISSING_SOP_ERR_MASK 0x1
#define XUSB3_PTP_GUARD_2CORE_IRQ0_PENDING_IRQ_MISSING_SOP_ERR 0x1
#define XUSB3_PTP_GUARD_2CORE_IRQ0_RAW_MAX_CYCLE_ERR_OFFSET 2
#define XUSB3_PTP_GUARD_2CORE_IRQ0_RAW_MAX_CYCLE_ERR_MASK 0x4
#define XUSB3_PTP_GUARD_2CORE_IRQ0_RAW_MAX_CYCLE_ERR 0x4
#define XUSB3_PTP_GUARD_2CORE_IRQ0_RAW_MISSING_EOP_ERR_OFFSET 1
#define XUSB3_PTP_GUARD_2CORE_IRQ0_RAW_MISSING_EOP_ERR_MASK 0x2
#define XUSB3_PTP_GUARD_2CORE_IRQ0_RAW_MISSING_EOP_ERR 0x2
#define XUSB3_PTP_GUARD_2CORE_IRQ0_RAW_MISSING_SOP_ERR_OFFSET 0
#define XUSB3_PTP_GUARD_2CORE_IRQ0_RAW_MISSING_SOP_ERR_MASK 0x1
#define XUSB3_PTP_GUARD_2CORE_IRQ0_RAW_MISSING_SOP_ERR 0x1
#define XUSB3_BUFF_2ULP_CONTROL_CLR_OFFSET 0
#define XUSB3_BUFF_2ULP_CONTROL_CLR_MASK 0x1
#define XUSB3_BUFF_2ULP_CONTROL_CLR 0x1
#define XUSB3_BUFF_2ULP_STATS0_RD2CLR_CONFIG_PFIFO_DCOUNT_OFFSET 1
#define XUSB3_BUFF_2ULP_STATS0_RD2CLR_CONFIG_PFIFO_DCOUNT_MASK 0x2
#define XUSB3_BUFF_2ULP_STATS0_RD2CLR_CONFIG_PFIFO_DCOUNT 0x2
#define XUSB3_BUFF_2ULP_STATS0_RD2CLR_CONFIG_NFIFO_DCOUNT_OFFSET 0
#define XUSB3_BUFF_2ULP_STATS0_RD2CLR_CONFIG_NFIFO_DCOUNT_MASK 0x1
#define XUSB3_BUFF_2ULP_STATS0_RD2CLR_CONFIG_NFIFO_DCOUNT 0x1
#define XUSB3_BUFF_2ULP_STATS0_NFIFO_DCOUNT_NFIFO_DCOUNT_OFFSET 0
#define XUSB3_BUFF_2ULP_STATS0_NFIFO_DCOUNT_NFIFO_DCOUNT_MASK 0xFFFF
#define XUSB3_BUFF_2ULP_STATS0_PFIFO_DCOUNT_PFIFO_DCOUNT_OFFSET 0
#define XUSB3_BUFF_2ULP_STATS0_PFIFO_DCOUNT_PFIFO_DCOUNT_MASK 0xFFFF
#define XUSB3_BUFF_2UPP_CONTROL_CLR_OFFSET 0
#define XUSB3_BUFF_2UPP_CONTROL_CLR_MASK 0x1
#define XUSB3_BUFF_2UPP_CONTROL_CLR 0x1
#define XUSB3_BUFF_2UPP_STATS0_RD2CLR_CONFIG_PFIFO_SCOUNT_OFFSET 1
#define XUSB3_BUFF_2UPP_STATS0_RD2CLR_CONFIG_PFIFO_SCOUNT_MASK 0x2
#define XUSB3_BUFF_2UPP_STATS0_RD2CLR_CONFIG_PFIFO_SCOUNT 0x2
#define XUSB3_BUFF_2UPP_STATS0_RD2CLR_CONFIG_NFIFO_SCOUNT_OFFSET 0
#define XUSB3_BUFF_2UPP_STATS0_RD2CLR_CONFIG_NFIFO_SCOUNT_MASK 0x1
#define XUSB3_BUFF_2UPP_STATS0_RD2CLR_CONFIG_NFIFO_SCOUNT 0x1
#define XUSB3_BUFF_2UPP_STATS0_NFIFO_SCOUNT_NFIFO_SCOUNT_OFFSET 0
#define XUSB3_BUFF_2UPP_STATS0_NFIFO_SCOUNT_NFIFO_SCOUNT_MASK 0xFFFF
#define XUSB3_BUFF_2UPP_STATS0_PFIFO_SCOUNT_PFIFO_SCOUNT_OFFSET 0
#define XUSB3_BUFF_2UPP_STATS0_PFIFO_SCOUNT_PFIFO_SCOUNT_MASK 0xFFFF
#define XUSB3_IRQ0_ENABLE_LINK_PARTNER_PTP_VIOLATED_OFFSET 0
#define XUSB3_IRQ0_ENABLE_LINK_PARTNER_PTP_VIOLATED_MASK 0x1
#define XUSB3_IRQ0_ENABLE_LINK_PARTNER_PTP_VIOLATED 0x1
#define XUSB3_IRQ0_PENDING_LINK_PARTNER_PTP_VIOLATED_OFFSET 0
#define XUSB3_IRQ0_PENDING_LINK_PARTNER_PTP_VIOLATED_MASK 0x1
#define XUSB3_IRQ0_PENDING_LINK_PARTNER_PTP_VIOLATED 0x1
#define XUSB3_IRQ0_PENDING_IRQ_LINK_PARTNER_PTP_VIOLATED_OFFSET 0
#define XUSB3_IRQ0_PENDING_IRQ_LINK_PARTNER_PTP_VIOLATED_MASK 0x1
#define XUSB3_IRQ0_PENDING_IRQ_LINK_PARTNER_PTP_VIOLATED 0x1
#define XUSB3_IRQ0_RAW_LINK_PARTNER_PTP_VIOLATED_OFFSET 0
#define XUSB3_IRQ0_RAW_LINK_PARTNER_PTP_VIOLATED_MASK 0x1
#define XUSB3_IRQ0_RAW_LINK_PARTNER_PTP_VIOLATED 0x1
#endif /* _XUSB3_REGS_H_ */

/* end */
