#ifndef _PROJECT_COMPONENTS_H
#define _PROJECT_COMPONENTS_H
#include <icomponent.h>


COMPONENT_LIST_CREATE()
    COMPONENT_CREATE(TEST_COMPONENT)
    COMPONENT_CREATE(ILOG_COMPONENT)
COMPONENT_LIST_END()

#endif // #ifndef _PROJECT_COMPONENTS_H

