//#################################################################################################
// Icron Technology Corporation - Copyright 2017
//
// This source file and the information contained in it are confidential and proprietary to Icron
// Technology Corporation. The reproduction or disclosure, in whole or in part, to anyone outside
// of Icron without the written approval of a Icron officer under a Non-Disclosure Agreement, or to
// any employee of Icron who has not previously obtained written authorization for access from the
// individual responsible for the source code, will have a significant detrimental effect on Icron
// and is expressly prohibited.
//#################################################################################################

//#################################################################################################
// Module Description
//#################################################################################################
// Aquantia AQR105 Stat monitoring parts
//#################################################################################################

//#################################################################################################
// Design Notes
//#################################################################################################
//#################################################################################################

// Includes #######################################################################################
#include <ibase.h>
#include <bb_top.h>
#include <mdio.h>
#include <stats_mon.h>
#include <aquantia_stat.h>
#include <configuration.h>
#include <led.h>
#include <sys_funcs.h>
#include "aquantia_log.h"
#include "aquantia_loc.h"
#include "aquantia_regs.h"

// Constants and Macros ###########################################################################

#define AQUANTIA_STATS_POLL_INTERVAL     ((3*1000)/STATISTIC_INTERVAL_TICK)        // poll the Aquantia stats every 3 seconds

// Display when it changes with accumulating value
#define AQUANTIA_STAT_MDIO_REG_CHANGE_REL( \
        regAddress1, \
        regAddress2, \
        devType, \
        ilogCode, \
        bitMask, \
        bitOffset) \
        STATMON_AQUANTIA_READ_PARAM( \
            regAddress1, \
            regAddress2, \
            devType, \
            STATMON_PARAM_FLAG_RELATIVE_VALUE, \
            AQUANTIA_COMPONENT, \
            ilogCode, \
            bitMask, \
            bitOffset)

// Display when it changes without accumulate value
#define AQUANTIA_STAT_MDIO_REG_CHANGE( \
        regAddress1, \
        regAddress2, \
        devType, \
        ilogCode, \
        bitMask, \
        bitOffset) \
        STATMON_AQUANTIA_READ_PARAM( \
            regAddress1, \
            regAddress2, \
            devType, \
            0, \
            AQUANTIA_COMPONENT, \
            ilogCode, \
            bitMask, \
            bitOffset)

#define AQUANTIA_STAT_MDIO_REG_CHANGE_SET( \
        regAddress1, \
        regAddress2, \
        devType, \
        ilogCode, \
        bitMask, \
        bitOffset) \
        STATMON_AQUANTIA_READ_PARAM( \
            regAddress1, \
            regAddress2, \
            devType, \
            STATMON_PARAM_FLAG_SET, \
            AQUANTIA_COMPONENT, \
            ilogCode, \
            bitMask, \
            bitOffset)

#define AQUANTIA_STAT_MDIO_REG_CHANGE_CLR( \
        regAddress1, \
        regAddress2, \
        devType, \
        ilogCode, \
        bitMask, \
        bitOffset) \
        STATMON_AQUANTIA_READ_PARAM( \
            regAddress1, \
            regAddress2, \
            devType, \
            STATMON_PARAM_FLAG_CLR, \
            AQUANTIA_COMPONENT, \
            ilogCode, \
            bitMask, \
            bitOffset)

// Display when it changes with accumulating value - print with red character
#define AQUANTIA_STAT_MDIO_REG_CHANGE_REL_CRITICAL( \
        regAddress1, \
        regAddress2, \
        devType, \
        ilogCode, \
        bitMask, \
        bitOffset) \
        STATMON_AQUANTIA_READ_PARAM( \
            regAddress1, \
            regAddress2, \
            devType, \
            STATMON_PARAM_FLAG_RELATIVE_VALUE | STATMON_PARAM_MAJOR_DISPLAY, \
            AQUANTIA_COMPONENT, \
            ilogCode, \
            bitMask, \
            bitOffset)

// Display when it changes without accumulate value - print with red character
#define AQUANTIA_STAT_MDIO_REG_CHANGE_CRITICAL( \
        regAddress1, \
        regAddress2, \
        devType, \
        ilogCode, \
        bitMask, \
        bitOffset) \
        STATMON_AQUANTIA_READ_PARAM( \
            regAddress1, \
            regAddress2, \
            devType, \
            STATMON_PARAM_MAJOR_DISPLAY, \
            AQUANTIA_COMPONENT, \
            ilogCode, \
            bitMask, \
            bitOffset)

// Display when it changes with accumulating value - print with istatus
#define AQUANTIA_STAT_MDIO_REG_CHANGE_REL_ISTATUS( \
        regAddress1, \
        regAddress2, \
        devType, \
        iStatusCode, \
        bitMask, \
        bitOffset) \
        STATMON_AQUANTIA_READ_PARAM( \
            regAddress1, \
            regAddress2, \
            devType, \
            STATMON_PARAM_FLAG_RELATIVE_VALUE | STATMON_PARAM_ISTATUS_DISPLAY, \
            AQUANTIA_COMPONENT, \
            iStatusCode, \
            bitMask, \
            bitOffset)

// Display when it changes without accumulating value - print with istatus
#define AQUANTIA_STAT_MDIO_REG_CHANGE_ISTATUS( \
        regAddress1, \
        regAddress2, \
        devType, \
        iStatusCode, \
        bitMask, \
        bitOffset) \
        STATMON_AQUANTIA_READ_PARAM( \
            regAddress1, \
            regAddress2, \
            devType, \
            STATMON_PARAM_ISTATUS_DISPLAY, \
            AQUANTIA_COMPONENT, \
            iStatusCode, \
            bitMask, \
            bitOffset)

#define AQUANTIA_STAT_MDIO_REG_CHANGE_SET_CRITICAL( \
        regAddress1, \
        regAddress2, \
        devType, \
        ilogCode, \
        bitMask, \
        bitOffset) \
        STATMON_AQUANTIA_READ_PARAM( \
            regAddress1, \
            regAddress2, \
            devType, \
            STATMON_PARAM_MAJOR_DISPLAY | STATMON_PARAM_FLAG_SET , \
            AQUANTIA_COMPONENT, \
            ilogCode, \
            bitMask, \
            bitOffset)

#define AQUANTIA_STAT_MDIO_REG_CHANGE_CLR_CRITICAL( \
        regAddress1, \
        regAddress2, \
        devType, \
        ilogCode, \
        bitMask, \
        bitOffset) \
        STATMON_AQUANTIA_READ_PARAM( \
            regAddress1, \
            regAddress2, \
            devType, \
            STATMON_PARAM_MAJOR_DISPLAY | STATMON_PARAM_FLAG_CLR , \
            AQUANTIA_COMPONENT, \
            ilogCode, \
            bitMask, \
            bitOffset)

// Data Types #####################################################################################

// Global Variables ###############################################################################

// Static Variables ###############################################################################
static const StatAquantiaReg AquantiaStatU8Regs[] =                    // Array of monitoring stats for 8bits data
{
    AQUANTIA_STAT_MDIO_REG_CHANGE_CLR(          PMA_RECEIVE_LINK_STATUS_ADDR,            AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PMD_PMA,   AQUANTIA_PMA_RECEIVE_LINK_STATUS,                   PMA_RECEIVE_LINK_STATUS_MASK,            PMA_RECEIVE_LINK_STATUS_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET_CRITICAL( PMA_STANDARD_STATUS_2_ADDR,              AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PMD_PMA,   AQUANTIA_PMA_TRANSMIT_FAULT,                        PMA_TRANSMIT_FAULT_MASK,                 PMA_TRANSMIT_FAULT_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET_CRITICAL( PMA_STANDARD_STATUS_2_ADDR,              AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PMD_PMA,   AQUANTIA_PMA_RECEIVE_FAULT,                         PMA_RECEIVE_FAULT_MASK,                  PMA_RECEIVE_FAULT_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE(              PMA_FAST_RETRAIN_STATUS_ADDR,            AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PMD_PMA,   AQUANTIA_PMA_LP_RETRAIN_COUNT,                      PMA_LP_RETRAIN_MASK,                     PMA_LP_RETRAIN_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE(              PMA_FAST_RETRAIN_STATUS_ADDR,            AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PMD_PMA,   AQUANTIA_PMA_LD_RETRAIN_COUNT,                      PMA_LD_RETRAIN_MASK,                     PMA_LD_RETRAIN_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE(              PMA_FAST_RETRAIN_STATUS_ADDR,            AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PMD_PMA,   AQUANTIA_PMA_RETRAIN_SIGNAL_TYPE,                   PMA_RETRAIN_SIGNAL_TYPE_MASK,            PMA_RETRAIN_SIGNAL_TYPE_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_CRITICAL(     PMA_RECEIVE_VENDOR_STATE_2_ADDR,         AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PMD_PMA,   AQUANTIA_PMA_NUM_LINK_RECOVERY,                     PMA_NUM_RFI_RECOVERY_MASK,               PMA_NUM_RFI_RECOVERY_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_CRITICAL(     PMA_RECEIVE_VENDOR_STATE_2_ADDR,         AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PMD_PMA,   AQUANTIA_PMA_NUM_RFI_RECOVERY,                      PMA_NUM_RFI_RECOVERY_MASK,               PMA_NUM_RFI_RECOVERY_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE(              PMA_RECEIVE_CURRENT_LINK_STATUS_ADDR,    AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PMD_PMA,   AQUANTIA_PMA_RECEIVE_CURRENT_LINK_STATUS,           PMA_RECEIVE_CURRENT_LINK_STATUS_MASK,    PMA_RECEIVE_CURRENT_LINK_STATUS_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE(              PCS_STANDARD_STATUS_1_ADDR,              AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PCS,       AQUANTIA_PCS_FAULT_STATUS,                          PCS_FAULT_MASK,                          PCS_FAULT_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_CLR(          PCS_STANDARD_STATUS_1_ADDR,              AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PCS,       AQUANTIA_PCS_RECEIVE_LINK_STATUS,                   PCS_RECEIVE_LINK_STATUS_MASK,            PCS_RECEIVE_LINK_STATUS_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET_CRITICAL( PCS_STANDARD_STATUS_2_ADDR,              AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PCS,       AQUANTIA_PCS_TRANSMIT_FAULT,                        PCS_TRANSMIT_FAULT_MASK,                 PCS_TRANSMIT_FAULT_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET_CRITICAL( PCS_STANDARD_STATUS_2_ADDR,              AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PCS,       AQUANTIA_PCS_RECEIVE_FAULT,                         PCS_RECEIVE_FAULT_MASK,                  PCS_RECEIVE_FAULT_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE(              PCS_10G_STATUS_1_ADDR,                   AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PCS,       AQUANTIA_PCS_10G_LINK_STATUS,                       PCS_10G_LINK_STATUS_MASK,                PCS_10G_LINK_STATUS_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_CRITICAL(     PCS_10G_STATUS_1_ADDR,                   AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PCS,       AQUANTIA_PCS_10G_BLOCK_LOCK,                        PCS_10G_BLOCK_LOCK_MASK,                 PCS_10G_BLOCK_LOCK_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_CRITICAL(     PCS_10G_STATUS_1_ADDR,                   AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PCS,       AQUANTIA_PCS_10G_HIGH_BER,                          PCS_10G_HIGH_BER_MASK,                   PCS_10G_HIGH_BER_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_CLR(          PCS_10G_STATUS_2_ADDR,                   AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PCS,       AQUANTIA_PCS_BLOCK_LOCK_LATCHED,                    PCS_BLOCK_LOCK_LATCHED_MASK,             PCS_BLOCK_LOCK_LATCHED_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET(          PCS_10G_STATUS_2_ADDR,                   AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PCS,       AQUANTIA_PCS_HIGH_BER_LATCHED,                      PCS_HIGH_BER_LATCHED_MASK,               PCS_HIGH_BER_LATCHED_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_CRITICAL(     PCS_10G_STATUS_2_ADDR,                   AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PCS,       AQUANTIA_PCS_ERROR_FRAME_COUNT,                     PCS_ERROR_FRAME_COUNT_MASK,              PCS_ERROR_FRAME_COUNT_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_CRITICAL(     PCS_10G_STATUS_2_ADDR,                   AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PCS,       AQUANTIA_PCS_ERROR_BLOCK_COUNT,                     PCS_ERROR_BLOCK_COUNT_MASK,              PCS_ERROR_BLOCK_COUNT_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_CRITICAL(     PCS_SYSTEM_INTERFACE_FAULT_ADDR,         AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PCS,       AQUANTIA_PCS_SYSTEM_INTERFACE_FAULT,                PCS_SYSTEM_INTERFACE_FAULT_MASK,         PCS_SYSTEM_INTERFACE_FAULT_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET_CRITICAL( PCS_XAUI_INVALID_BLOCK_ADDR,             AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PCS,       AQUANTIA_PCS_XAUI_INVALID_BLOCK,                    PCS_XAUI_INVALID_BLOCK_MASK,             PCS_XAUI_INVALID_BLOCK_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET(          PCS_VENDOR_ALARMS_1_ADDR,                AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PCS,       AQUANTIA_PCS_CRC_ERROR,                             PCS_CRC_ERROR_MASK,                      PCS_CRC_ERROR_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET(          PCS_VENDOR_ALARMS_1_ADDR,                AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PCS,       AQUANTIA_PCS_LDPC_DECODE_FAILURE,                   PCS_LDPC_DECODE_FAILURE_MASK,            PCS_LDPC_DECODE_FAILURE_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET(          PCS_VENDOR_ALARMS_1_ADDR,                AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PCS,       AQUANTIA_PCS_LOCAL_FAULT_DETECT,                    PCS_LOCAL_FAULT_DETECT_MASK,             PCS_LOCAL_FAULT_DETECT_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET(          PCS_VENDOR_ALARMS_1_ADDR,                AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PCS,       AQUANTIA_PCS_LOF_DETECT,                            PCS_LOF_DETECT_MASK,                     PCS_LOF_DETECT_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET(          PCS_VENDOR_ALARMS_1_ADDR,                AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PCS,       AQUANTIA_PCS_40G_BIP_LOCK,                          PCS_40G_BIP_LOCK_MASK,                   PCS_40G_BIP_LOCK_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET(          PCS_VENDOR_ALARMS_1_ADDR,                AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PCS,       AQUANTIA_PCS_INVALID_65B_BLOCK,                     PCS_INVALID_65B_BLOCK_MASK,              PCS_INVALID_65B_BLOCK_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET(          PCS_VENDOR_ALARMS_1_ADDR,                AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PCS,       AQUANTIA_PCS_LDPC_ERROR_EXCEEDED,                   PCS_LDPC_ERROR_EXCEEDED_MASK,            PCS_LDPC_ERROR_EXCEEDED_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_CLR(          PHY_TRANSMIT_LINK_ALIGNMENT_STATUS_ADDR, AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PHY_XS,    AQUANTIA_PHY_TRANSMIT_LINK_ALIGNMENT_STATUS,        PHY_TRANSMIT_LINK_ALIGNMENT_STATUS_MASK, PHY_TRANSMIT_LINK_ALIGNMENT_STATUS_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET_CRITICAL( PHY_STANDARD_STATUS_2_ADDR,              AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PHY_XS,    AQUANTIA_PHY_TX_FAULT,                              PHY_TX_FAULT_MASK,                       PHY_TX_FAULT_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET_CRITICAL( PHY_STANDARD_STATUS_2_ADDR,              AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PHY_XS,    AQUANTIA_PHY_RX_FAULT,                              PHY_RX_FAULT_MASK,                       PHY_RX_FAULT_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE(              PHY_XGXS_LANE_STATUS_ADDR,               AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PHY_XS,    AQUANTIA_PHY_XGXS_LANE_ALIGN,                       PHY_XGXS_LANE_ALIGN_MASK,                PHY_XGXS_LANE_ALIGN_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE(              PHY_XGXS_LANE_STATUS_ADDR,               AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PHY_XS,    AQUANTIA_PHY_LANE_SYNC,                             PHY_XGXS_LANE_SYNC_MASK,                 PHY_XGXS_LANE_SYNC_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_CRITICAL(     PHY_TRANSMIT_VENDOR_STATE_2_ADDR,        AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PHY_XS,    AQUANTIA_PHY_SIF_BLOCK_LOCK_TRANSITIONS_1_0_NUMBER, PHY_SIF_BLOCK_LOCK_TRANSITIONS_1_0_MASK, PHY_SIF_BLOCK_LOCK_TRANSITIONS_1_0_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_CRITICAL(     PHY_TRANSMIT_VENDOR_STATE_2_ADDR,        AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PHY_XS,    AQUANTIA_PHY_SIF_BLOCK_LOCK_TRANSITIONS_0_1_NUMBER, PHY_SIF_BLOCK_LOCK_TRANSITIONS_0_1_MASK, PHY_SIF_BLOCK_LOCK_TRANSITIONS_0_1_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET_CRITICAL( PHY_TRANSMIT_VENDOR_ALARMS_2_ADDR,       AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PHY_XS,    AQUANTIA_PHY_XAUI_RX_DELETION,                      PHY_XAUI_RX_DELETION_MASK,               PHY_XAUI_RX_DELETION_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_CLR_CRITICAL( PHY_TRANSMIT_VENDOR_ALARMS_2_ADDR,       AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PHY_XS,    AQUANTIA_PHY_RXAUI_LANE_ALIGN_LOCK_A,               PHY_RXAUI_LANE_ALIGN_LOCK_MASK_1,        PHY_RXAUI_LANE_ALIGN_LOCK_OFFSET_1),
    AQUANTIA_STAT_MDIO_REG_CHANGE_CLR_CRITICAL( PHY_TRANSMIT_VENDOR_ALARMS_2_ADDR,       AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PHY_XS,    AQUANTIA_PHY_RXAUI_LANE_ALIGN_LOCK_B,               PHY_RXAUI_LANE_ALIGN_LOCK_MASK_2,        PHY_RXAUI_LANE_ALIGN_LOCK_OFFSET_2),
    AQUANTIA_STAT_MDIO_REG_CHANGE_CRITICAL(     PHY_TRANSMIT_VENDOR_ALARMS_2_ADDR,       AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PHY_XS,    AQUANTIA_PHY_TX_RESERVED_XGMII_CHAR,                PHY_TX_RESERVED_XGMII_CHAR_MASK,         PHY_TX_RESERVED_XGMII_CHAR_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_CRITICAL(     PHY_TRANSMIT_VENDOR_ALARMS_2_ADDR,       AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PHY_XS,    AQUANTIA_PHY_TX_INVALID_XGMII_CHAR,                 PHY_TX_INVALID_XGMII_CHAR_MASK,          PHY_TX_INVALID_XGMII_CHAR_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET_CRITICAL( PHY_TRANSMIT_VENDOR_ALARMS_2_ADDR,       AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PHY_XS,    AQUANTIA_PHY_TX_CODE_VIOLATION_ERR_1,               PHY_TX_CODE_VIOLATION_ERR_MASK_1,        PHY_TX_CODE_VIOLATION_ERR_OFFSET_1),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET_CRITICAL( PHY_TRANSMIT_VENDOR_ALARMS_2_ADDR,       AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PHY_XS,    AQUANTIA_PHY_TX_CODE_VIOLATION_ERR_2,               PHY_TX_CODE_VIOLATION_ERR_MASK_2,        PHY_TX_CODE_VIOLATION_ERR_OFFSET_2),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET_CRITICAL( PHY_TRANSMIT_VENDOR_ALARMS_2_ADDR,       AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PHY_XS,    AQUANTIA_PHY_TX_CODE_VIOLATION_ERR_3,               PHY_TX_CODE_VIOLATION_ERR_MASK_3,        PHY_TX_CODE_VIOLATION_ERR_OFFSET_3),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET_CRITICAL( PHY_TRANSMIT_VENDOR_ALARMS_2_ADDR,       AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PHY_XS,    AQUANTIA_PHY_TX_CODE_VIOLATION_ERR_4,               PHY_TX_CODE_VIOLATION_ERR_MASK_4,        PHY_TX_CODE_VIOLATION_ERR_OFFSET_4),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET_CRITICAL( PHY_TRANSMIT_VENDOR_ALARMS_2_ADDR,       AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PHY_XS,    AQUANTIA_PHY_TX_RUN_DISPARITY_ERR_1,                PHY_TX_RUN_DISPARITY_ERR_MASK_1,         PHY_TX_RUN_DISPARITY_ERR_OFFSET_1),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET_CRITICAL( PHY_TRANSMIT_VENDOR_ALARMS_2_ADDR,       AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PHY_XS,    AQUANTIA_PHY_TX_RUN_DISPARITY_ERR_2,                PHY_TX_RUN_DISPARITY_ERR_MASK_2,         PHY_TX_RUN_DISPARITY_ERR_OFFSET_2),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET_CRITICAL( PHY_TRANSMIT_VENDOR_ALARMS_2_ADDR,       AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PHY_XS,    AQUANTIA_PHY_TX_RUN_DISPARITY_ERR_3,                PHY_TX_RUN_DISPARITY_ERR_MASK_3,         PHY_TX_RUN_DISPARITY_ERR_OFFSET_3),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET_CRITICAL( PHY_TRANSMIT_VENDOR_ALARMS_2_ADDR,       AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PHY_XS,    AQUANTIA_PHY_TX_RUN_DISPARITY_ERR_4,                PHY_TX_RUN_DISPARITY_ERR_MASK_4,         PHY_TX_RUN_DISPARITY_ERR_OFFSET_4),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET_CRITICAL( PHY_TRANSMIT_VENDOR_ALARMS_3_ADDR,       AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PHY_XS,    AQUANTIA_PHY_SIGNAL_LOSS_1,                         PHY_SIGNAL_LOSS_MASK_1,                  PHY_SIGNAL_LOSS_OFFSET_1),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET_CRITICAL( PHY_TRANSMIT_VENDOR_ALARMS_3_ADDR,       AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PHY_XS,    AQUANTIA_PHY_SIGNAL_LOSS_2,                         PHY_SIGNAL_LOSS_MASK_2,                  PHY_SIGNAL_LOSS_OFFSET_2),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET_CRITICAL( PHY_TRANSMIT_VENDOR_ALARMS_3_ADDR,       AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PHY_XS,    AQUANTIA_PHY_SIGNAL_LOSS_3,                         PHY_SIGNAL_LOSS_MASK_3,                  PHY_SIGNAL_LOSS_OFFSET_3),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET_CRITICAL( PHY_TRANSMIT_VENDOR_ALARMS_3_ADDR,       AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PHY_XS,    AQUANTIA_PHY_SIGNAL_LOSS_4,                         PHY_SIGNAL_LOSS_MASK_4,                  PHY_SIGNAL_LOSS_OFFSET_4),
    AQUANTIA_STAT_MDIO_REG_CHANGE(              PHY_RECEIVE_VENDOR_STATE_E_ADDR,         AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PHY_XS,    AQUANTIA_PHY_AUTONEGO_STATUS,                       PHY_AUTONEGO_STATUS_MASK,                PHY_AUTONEGO_STATUS_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE(              PHY_RECEIVE_VENDOR_STATE_E_ADDR,         AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PHY_XS,    AQUANTIA_PHY_RX_LINK_UP,                            PHY_RX_LINK_UP_MASK,                     PHY_RX_LINK_UP_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE(              PHY_RECEIVE_VENDOR_STATE_E_ADDR,         AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PHY_XS,    AQUANTIA_PHY_TX_READY,                              PHY_TX_READY_MASK,                    PHY_RX_TX_READY_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET_CRITICAL( PHY_RECEIVE_VENDOR_ALARMS_1_ADDR,        AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PHY_XS,    AQUANTIA_PHY_RX_RESERVED_XGMII_CHAR,                PHY_RX_RESERVED_XGMII_CHAR_MASK,         PHY_RX_RESERVED_XGMII_CHAR_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET_CRITICAL( PHY_RECEIVE_VENDOR_ALARMS_1_ADDR,        AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PHY_XS,    AQUANTIA_PHY_RX_INVALID_XGMII_CHAR,                 PHY_RX_INVALID_XGMII_CHAR_MASK,          PHY_RX_INVALID_XGMII_CHAR_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET_CRITICAL( PHY_RECEIVE_VENDOR_ALARMS_1_ADDR,        AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PHY_XS,    AQUANTIA_PHY_RX_LINK_STATUS_MSG,                    PHY_RX_LINK_STATUS_MSG_MASK,             PHY_RX_LINK_STATUS_MSG_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET(          AUTONEG_STANDARD_STATUS_1_ADDR,          AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_AUTO_NEGO, AQUANTIA_AUTONEG_PARALLEL_DETECTION_FAULT,          AUTONEG_PARALLEL_DETECTION_FAULT_MASK,   AUTONEG_PARALLEL_DETECTION_FAULT_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET(          AUTONEG_STANDARD_STATUS_1_ADDR,          AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_AUTO_NEGO, AQUANTIA_AUTONEG_REMOTE_FAULT,                      AUTONEG_REMOTE_FAULT_MASK,               AUTONEG_REMOTE_FAULT_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_CLR_CRITICAL( AUTONEG_STANDARD_STATUS_1_ADDR,          AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_AUTO_NEGO, AQUANTIA_AUTONEG_LINK_STATUS,                       AUTONEG_LINK_STATUS_MASK,                AUTONEG_LINK_STATUS_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET_CRITICAL( AUTONEG_10GBASE_T_STATUS_ADDR,           AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_AUTO_NEGO, AQUANTIA_AUTONEG_MASTER_SLAVE_CONFIG_FAULT,         AUTONEG_MASTER_SLAVE_CONFIG_FAULT_MASK,  AUTONEG_MASTER_SLAVE_CONFIG_FAULT_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE(              AUTONEG_10GBASE_T_STATUS_ADDR,           AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_AUTO_NEGO, AQUANTIA_AUTONEG_LOCAL_RECEIVER_STATUS,             AUTONEG_LOCAL_RECEIVER_MASK,             AUTONEG_LOCAL_RECEIVER_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE(              AUTONEG_10GBASE_T_STATUS_ADDR,           AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_AUTO_NEGO, AQUANTIA_AUTONEG_REMOTE_RECEIVER_STATUS,            AUTONEG_REMOTE_RECEIVER_MASK,            AUTONEG_REMOTE_RECEIVER_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE(              AUTONEG_LINK_PULSE_DETECTED_ADDR,        AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_AUTO_NEGO, AQUANTIA_AUTONEG_LINK_PULSE_DETECTED_STATUS,        AUTONEG_LINK_PULSE_DETECTED_MASK,        AUTONEG_LINK_PULSE_DETECTED_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET_CRITICAL( AUTONEG_TRANSMIT_VENDOR_ALARMS_1_ADDR,   AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_AUTO_NEGO, AQUANTIA_AUTONEG_AUTOMATIC_DOWNSHIFT,               AUTONEG_AUTOMATIC_DOWNSHIFT_MASK,        AUTONEG_AUTOMATIC_DOWNSHIFT_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET_CRITICAL( AUTONEG_TRANSMIT_VENDOR_ALARMS_1_ADDR,   AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_AUTO_NEGO, AQUANTIA_AUTONEG_CONNECTION_STATE_CHANGE,           AUTONEG_CONNECTION_STATE_CHANGE_MASK,    AUTONEG_CONNECTION_STATE_CHANGE_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET_CRITICAL( AUTONEG_TRANSMIT_VENDOR_ALARMS_2_ADDR,   AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_AUTO_NEGO, AQUANTIA_AUTONEG_LINK_PULSE_DETECT,                 AUTONEG_LINK_PULSE_DETECT_MASK,          AUTONEG_LINK_PULSE_DETECT_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET_CRITICAL( AUTONEG_TRANSMIT_VENDOR_ALARMS_2_ADDR,   AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_AUTO_NEGO, AQUANTIA_AUTONEG_LINK_CONNECT,                      AUTONEG_LINK_CONNECT_MASK,               AUTONEG_LINK_CONNECT_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE(              AUTONEG_RECEIVE_VENDOR_PROV_ADDR,        AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_AUTO_NEGO, AQUANTIA_AUTONEG_10G_DOWNSHIFT,                     AUTONEG_10G_DOWNSHIFT_MASK,              AUTONEG_10G_DOWNSHIFT_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE(              AUTONEG_RECEIVE_VENDOR_PROV_ADDR,        AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_AUTO_NEGO, AQUANTIA_AUTONEG_5G_DOWNSHIFT,                      AUTONEG_5G_DOWNSHIFT_MASK,               AUTONEG_5G_DOWNSHIFT_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE(              AUTONEG_RECEIVE_VENDOR_PROV_ADDR,        AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_AUTO_NEGO, AQUANTIA_AUTONEG_2G_DOWNSHIFT,                      AUTONEG_2G_DOWNSHIFT_MASK,               AUTONEG_2G_DOWNSHIFT_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE(              AUTONEG_RECEIVE_VENDOR_PROV_ADDR,        AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_AUTO_NEGO, AQUANTIA_AUTONEG_1G_DOWNSHIFT,                      AUTONEG_1G_DOWNSHIFT_MASK,               AUTONEG_1G_DOWNSHIFT_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE(              AUTONEG_RECEIVE_VENDOR_PROV_ADDR,        AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_AUTO_NEGO, AQUANTIA_AUTONEG_MAX_ADVERTISED_RATE,               AUTONEG_MAX_ADVERTISED_RATE_MASK,        AUTONEG_MAX_ADVERTISED_RATE_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET(          AUTONEG_RECEIVED_VENDOR_ALARMS_2_ADDR,   AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_AUTO_NEGO, AQUANTIA_AUTONEG_PROTOCOL_ERROR,                    AUTONEG_PROTOCOL_ERROR_MASK,             AUTONEG_PROTOCOL_ERROR_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET(          AUTONEG_RECEIVED_VENDOR_ALARMS_2_ADDR,   AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_AUTO_NEGO, AQUANTIA_AUTONEG_FLP_IDLE_ERROR,                    AUTONEG_FLP_IDLE_ERROR_MASK,             AUTONEG_FLP_IDLE_ERROR_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_CRITICAL(     GLOBAL_GENERAL_STATUS_1_ADDR,             AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_GLOBAL,    AQUANTIA_GLOBAL_HIGH_TEMP_FAILURE_STATE,            GLOBAL_HIGH_TEMP_FAILURE_STATE_MASK,     GLOBAL_HIGH_TEMP_FAILURE_STATE_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_CRITICAL(     GLOBAL_GENERAL_STATUS_1_ADDR,             AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_GLOBAL,    AQUANTIA_GLOBAL_LOW_TEMP_FAILURE_STATE,             GLOBAL_LOW_TEMP_FAILURE_STATE_MASK,      GLOBAL_LOW_TEMP_FAILURE_STATE_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_CRITICAL(     GLOBAL_GENERAL_STATUS_1_ADDR,             AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_GLOBAL,    AQUANTIA_GLOBAL_HIGH_TEMP_WARNING_STATE,            GLOBAL_HIGH_TEMP_WARNING_STATE_MASK,     GLOBAL_HIGH_TEMP_WARNING_STATE_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_CRITICAL(     GLOBAL_GENERAL_STATUS_1_ADDR,             AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_GLOBAL,    AQUANTIA_GLOBAL_LOW_TEMP_WARNING_STATE,             GLOBAL_LOW_TEMP_WARNING_STATE_MASK,      GLOBAL_LOW_TEMP_WARNING_STATE_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET_CRITICAL( GLOBAL_ALARMS_1_ADDR,                     AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_GLOBAL,    AQUANTIA_GLOBAL_HIGH_TEMP_FAIL,                     GLOBAL_HIGH_TEMP_FAIL_MASK,              GLOBAL_HIGH_TEMP_FAIL_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET_CRITICAL( GLOBAL_ALARMS_1_ADDR,                     AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_GLOBAL,    AQUANTIA_GLOBAL_LOW_TEMP_FAIL,                      GLOBAL_LOW_TEMP_FAIL_MASK,               GLOBAL_LOW_TEMP_FAIL_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET_CRITICAL( GLOBAL_ALARMS_1_ADDR,                     AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_GLOBAL,    AQUANTIA_GLOBAL_HIGH_TEMP_WARNING,                  GLOBAL_HIGH_TEMP_WARNING_MASK,           GLOBAL_HIGH_TEMP_WARNING_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET_CRITICAL( GLOBAL_ALARMS_1_ADDR,                     AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_GLOBAL,    AQUANTIA_GLOBAL_LOW_TEMP_WARNING,                   GLOBAL_LOW_TEMP_WARNING_MASK,            GLOBAL_LOW_TEMP_WARNING_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET_CRITICAL( GLOBAL_ALARMS_1_ADDR,                     AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_GLOBAL,    AQUANTIA_GLOBAL_DEVICE_FAULT,                       GLOBAL_DEVICE_FAULT_MASK,                GLOBAL_DEVICE_FAULT_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET_CRITICAL( GLOBAL_ALARMS_2_ADDR,                     AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_GLOBAL,    AQUANTIA_GLOBAL_FAST_LINK_DROP_FAULT,               GLOBAL_FAST_LINK_DROP_FAULT_MASK,        GLOBAL_FAST_LINK_DROP_FAULT_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_SET_CRITICAL( GLOBAL_ALARMS_2_ADDR,                     AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_GLOBAL,    AQUANTIA_GLOBAL_MDIOD_COMMAND_OVERFLOW,             GLOBAL_MDIOD_COMMAND_OVERFLOW_MASK,      GLOBAL_MDIOD_COMMAND_OVERFLOW_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_CRITICAL(     DTEXS_TX_LOCAL_FAULT_ADDR,                AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_DTE_XS,    AQUANTIA_DTEXS_TX_LOCAL_FAULT,                      DTEXS_TX_LOCAL_FAULT_MASK,               DTEXS_TX_LOCAL_FAULT_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_CRITICAL(     DTEXS_RX_LOCAL_FAULT_ADDR,                AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_DTE_XS,    AQUANTIA_DTEXS_RX_LOCAL_FAULT,                      DTEXS_RX_LOCAL_FAULT_MASK,               DTEXS_RX_LOCAL_FAULT_OFFSET),
};

static const StatAquantiaReg AquantiaStatU16Regs[] =                            // Array of monitoring stats for 16bits data
{
    AQUANTIA_STAT_MDIO_REG_CHANGE_REL(         PCS_LDPC_CORRECTED_F6_ITERATION_COUNT_ADDR, AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PCS,        AQUANTIA_PCS_LDPC_CORRECTED_F6_ITERATION_COUNT, AQUANTIA_NO_MASK, AQUANTIA_NO_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_REL(         PCS_LDPC_CORRECTED_F7_ITERATION_COUNT_ADDR, AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PCS,        AQUANTIA_PCS_LDPC_CORRECTED_F7_ITERATION_COUNT, AQUANTIA_NO_MASK, AQUANTIA_NO_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_REL(         PCS_LDPC_CORRECTED_F8_ITERATION_COUNT_ADDR, AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PCS,        AQUANTIA_PCS_LDPC_CORRECTED_F8_ITERATION_COUNT, AQUANTIA_NO_MASK, AQUANTIA_NO_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_REL_CRITICAL(PHY_USX_AUTONEGO_NUMBER_ADDR,               AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PHY_XS,     AQUANTIA_PHY_USX_AUTONEGO_NUMBER,               AQUANTIA_NO_MASK, AQUANTIA_NO_OFFSET),
    // AQUANTIA_STAT_MDIO_REG_CHANGE_CRITICAL(    PMA_CHANNEL_A_OPERATING_MARGIN_ADDR,        AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PMD_PMA,    AQUANTIA_PMA_CHANNEL_A_OPERATING_MARGIN,        AQUANTIA_NO_MASK, AQUANTIA_NO_OFFSET),
    // AQUANTIA_STAT_MDIO_REG_CHANGE_CRITICAL(    PMA_CHANNEL_B_OPERATING_MARGIN_ADDR,        AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PMD_PMA,    AQUANTIA_PMA_CHANNEL_B_OPERATING_MARGIN,        AQUANTIA_NO_MASK, AQUANTIA_NO_OFFSET),
    // AQUANTIA_STAT_MDIO_REG_CHANGE_CRITICAL(    PMA_CHANNEL_C_OPERATING_MARGIN_ADDR,        AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PMD_PMA,    AQUANTIA_PMA_CHANNEL_C_OPERATING_MARGIN,        AQUANTIA_NO_MASK, AQUANTIA_NO_OFFSET),
    // AQUANTIA_STAT_MDIO_REG_CHANGE_CRITICAL(    PMA_CHANNEL_D_OPERATING_MARGIN_ADDR,        AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PMD_PMA,    AQUANTIA_PMA_CHANNEL_D_OPERATING_MARGIN,        AQUANTIA_NO_MASK, AQUANTIA_NO_OFFSET),
    // AQUANTIA_STAT_MDIO_REG_CHANGE_CRITICAL(    PMA_CHANNEL_A_MINIMUM_MARGIN_ADDR,          AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PMD_PMA,    AQUANTIA_PMA_CHANNEL_A_MINIMUM_MARGIN,          AQUANTIA_NO_MASK, AQUANTIA_NO_OFFSET),
    // AQUANTIA_STAT_MDIO_REG_CHANGE_CRITICAL(    PMA_CHANNEL_B_MINIMUM_MARGIN_ADDR,          AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PMD_PMA,    AQUANTIA_PMA_CHANNEL_B_MINIMUM_MARGIN,          AQUANTIA_NO_MASK, AQUANTIA_NO_OFFSET),
    // AQUANTIA_STAT_MDIO_REG_CHANGE_CRITICAL(    PMA_CHANNEL_C_MINIMUM_MARGIN_ADDR,          AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PMD_PMA,    AQUANTIA_PMA_CHANNEL_C_MINIMUM_MARGIN,          AQUANTIA_NO_MASK, AQUANTIA_NO_OFFSET),
    // AQUANTIA_STAT_MDIO_REG_CHANGE_CRITICAL(    PMA_CHANNEL_D_MINIMUM_MARGIN_ADDR,          AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PMD_PMA,    AQUANTIA_PMA_CHANNEL_D_MINIMUM_MARGIN,          AQUANTIA_NO_MASK, AQUANTIA_NO_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE(             PMA_CHANNEL_A_RECEIVED_SIGNAL_POWER_ADDR,   AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PMD_PMA,    AQUANTIA_PMA_CHANNEL_A_RECEIVED_SIGNAL_POWER,   AQUANTIA_NO_MASK,  AQUANTIA_NO_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE(             PMA_CHANNEL_B_RECEIVED_SIGNAL_POWER_ADDR,   AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PMD_PMA,    AQUANTIA_PMA_CHANNEL_B_RECEIVED_SIGNAL_POWER,   AQUANTIA_NO_MASK,  AQUANTIA_NO_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE(             PMA_CHANNEL_C_RECEIVED_SIGNAL_POWER_ADDR,   AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PMD_PMA,    AQUANTIA_PMA_CHANNEL_C_RECEIVED_SIGNAL_POWER,   AQUANTIA_NO_MASK,  AQUANTIA_NO_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE(             PMA_CHANNEL_D_RECEIVED_SIGNAL_POWER_ADDR,   AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PMD_PMA,    AQUANTIA_PMA_CHANNEL_D_RECEIVED_SIGNAL_POWER,   AQUANTIA_NO_MASK,  AQUANTIA_NO_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE(             PMA_FAST_RETRAIN_TIME_ADDR,                 AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PMD_PMA,    AQUANTIA_PMA_FAST_RETRAIN_TIME,                 AQUANTIA_NO_MASK,  AQUANTIA_NO_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_CRITICAL(    PHY_SERDES_CALS_ADDR,                       AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PHY_XS,     AQUANTIA_PHY_SERDES_CALS_NUMBER,                AQUANTIA_NO_MASK,  AQUANTIA_NO_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_REL_CRITICAL(PHY_SIF_XGS_SWITCH_OVERS_ADDR,              AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_PHY_XS,     AQUANTIA_PHY_SIF_XGS_SWITCH_OVERS_NUMBER,       AQUANTIA_NO_MASK,  AQUANTIA_NO_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE(             AUTONEG_RESTARTS_HANDLED_ADDR,              AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_AUTO_NEGO,  AQUANTIA_AUTONEG_RESTARTS_HANDLED,              AQUANTIA_NO_MASK,  AQUANTIA_NO_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_REL_CRITICAL(GLOBAL_MESSAGE_ADDR,                        AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_GLOBAL,     AQUANTIA_GLOBAL_MESSAGE,                        AQUANTIA_NO_MASK,  AQUANTIA_NO_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_ISTATUS(     GLOBAL_THERMAL_STATUS_1_ADDR,               AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_GLOBAL,     ISTATUS_AQUANTIA_TEMP_WARNING,                  AQUANTIA_NO_MASK,  AQUANTIA_NO_OFFSET)
};

static const StatAquantiaReg AquantiaStatU32Regs[] =                            // Array of monitoring stats for 32bits data
{
//    AQUANTIA_STAT_MDIO_REG_CHANGE_REL_CRITICAL(PCS_TX_10G_BAD_FRAME_COUNTER_MSW_ADDR,          PCS_TX_10G_BAD_FRAME_COUNTER_LSW_ADDR,          MDIO_DEVTYPE_PCS,       AQUANTIA_PCS_TX_10G_BAD_FRAME_COUNT,            PCS_TX_10G_BAD_FRAME_COUNTER_MASK,          PCS_TX_10G_BAD_FRAME_COUNTER_OFFSET),
   AQUANTIA_STAT_MDIO_REG_CHANGE_REL_ISTATUS( PCS_CRC8_ERROR_COUNT_MSW_ADDR,                  PCS_CRC8_ERROR_COUNT_LSW_ADDR,                  MDIO_DEVTYPE_PCS,       ISTATUS_AQUANTIA_CRC8_ERROR_COUNT,              AQUANTIA_NO_MASK,                           AQUANTIA_NO_OFFSET),
//    AQUANTIA_STAT_MDIO_REG_CHANGE_REL_ISTATUS( PCS_10G_ERROR_FRAME_COUNT_MSW_ADDR,             PCS_10G_ERROR_FRAME_COUNT_LSW_ADDR,             MDIO_DEVTYPE_PCS,       ISTATUS_AQUANTIA_10G_ERROR_FRAME_COUNT,         PCS_10G_ERROR_FRAME_COUNT_MASK,             PCS_10G_ERROR_FRAME_COUNT_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_REL_CRITICAL(PCS_UNCORRECTED_FRAME_COUNT_MSW_ADDR,           PCS_UNCORRECTED_FRAME_COUNT_LSW_ADDR,           MDIO_DEVTYPE_PCS,       AQUANTIA_PCS_UNCORRECTED_FRAME_COUNT,           PCS_UNCORRECTED_FRAME_COUNT_MASK,           PCS_UNCORRECTED_FRAME_COUNT_OFFSET),
    // AQUANTIA_STAT_MDIO_REG_CHANGE_REL(         PCS_LDPC_CORRECTED_F2_ITERATION_COUNT_MSW_ADDR, PCS_LDPC_CORRECTED_F2_ITERATION_COUNT_LSW_ADDR, MDIO_DEVTYPE_PCS,       AQUANTIA_PCS_LDPC_CORRECTED_F2_ITERATION_COUNT, PCS_LDPC_CORRECTED_F2_ITERATION_COUNT_MASK, PCS_LDPC_CORRECTED_F2_ITERATION_COUNT_OFFSET),
    // AQUANTIA_STAT_MDIO_REG_CHANGE_REL(         PCS_LDPC_CORRECTED_F3_ITERATION_COUNT_MSW_ADDR, PCS_LDPC_CORRECTED_F3_ITERATION_COUNT_LSW_ADDR, MDIO_DEVTYPE_PCS,       AQUANTIA_PCS_LDPC_CORRECTED_F3_ITERATION_COUNT, PCS_LDPC_CORRECTED_F3_ITERATION_COUNT_MASK, PCS_LDPC_CORRECTED_F3_ITERATION_COUNT_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_REL(         PCS_LDPC_CORRECTED_F4_ITERATION_COUNT_MSW_ADDR, PCS_LDPC_CORRECTED_F4_ITERATION_COUNT_LSW_ADDR, MDIO_DEVTYPE_PCS,       AQUANTIA_PCS_LDPC_CORRECTED_F4_ITERATION_COUNT, PCS_LDPC_CORRECTED_F4_ITERATION_COUNT_MASK, PCS_LDPC_CORRECTED_F4_ITERATION_COUNT_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE_REL(         PCS_LDPC_CORRECTED_F5_ITERATION_COUNT_MSW_ADDR, PCS_LDPC_CORRECTED_F5_ITERATION_COUNT_LSW_ADDR, MDIO_DEVTYPE_PCS,       AQUANTIA_PCS_LDPC_CORRECTED_F5_ITERATION_COUNT, PCS_LDPC_CORRECTED_F5_ITERATION_COUNT_MASK, PCS_LDPC_CORRECTED_F5_ITERATION_COUNT_OFFSET),
//    AQUANTIA_STAT_MDIO_REG_CHANGE_REL_CRITICAL(PHY_TX_BAD_FRAME_COUNT_MSW_ADDR,                PHY_TX_BAD_FRAME_COUNT_LSW_ADDR,                MDIO_DEVTYPE_PHY_XS,    AQUANTIA_PHY_TX_BAD_FRAME_COUNT,                PHY_TX_BAD_FRAME_COUNT_MASK,                PHY_TX_BAD_FRAME_COUNT_OFFSET),
//    AQUANTIA_STAT_MDIO_REG_CHANGE_REL_CRITICAL(PHY_RX_BAD_FRAME_COUNT_MSW_ADDR,                PHY_RX_BAD_FRAME_COUNT_LSW_ADDR,                MDIO_DEVTYPE_PHY_XS,    AQUANTIA_PHY_RX_BAD_FRAME_COUNT,                PHY_RX_BAD_FRAME_COUNT_MASK,                PHY_RX_BAD_FRAME_COUNT_OFFSET),
//    AQUANTIA_STAT_MDIO_REG_CHANGE_REL(          PCS_LDPC_1_ITERATION_CORRECTED_FRAMES_MSW_ADDR, PCS_LDPC_1_ITERATION_CORRECTED_FRAMES_LSW_ADDR, MDIO_DEVTYPE_PCS,       AQUANTIA_PCS_LDPC_1_ITERATION_CORRECTED_FRAMES, PCS_LDPC_1_ITERATION_CORRECTED_FRAMES_MASK, PCS_LDPC_1_ITERATION_CORRECTED_FRAMES_OFFSET),

};

static const StatAquantiaReg AquantiaLinkDropRegs[]=                         // Array of monitoring stats for drop link
{
    AQUANTIA_STAT_MDIO_REG_CHANGE(AUTONEG_CONNECTION_STATE_ADDR, AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_AUTO_NEGO, AQUANTIA_AUTONEG_CONNECTION_STATE, AUTONEG_CONNECTION_STATE_MASK, AUTONEG_CONNECTION_STATE_OFFSET),
    AQUANTIA_STAT_MDIO_REG_CHANGE(AUTONEG_ATTEMPTS_SINCE_RESET_ADDR, AQUANTIA_NULL_ADDR, MDIO_DEVTYPE_AUTO_NEGO, AQUANTIA_AUTONEG_ATTEMPTS_SINCE_RESET, AQUANTIA_NO_MASK, AQUANTIA_NO_OFFSET),
};

static uint8_t AquantiaStatU8data[ARRAYSIZE(AquantiaStatU8Regs)];               // The place to store 8bits stat data
static uint16_t AquantiaStatU16data[ARRAYSIZE(AquantiaStatU16Regs)];            // The place to store 16bits stat data
static uint32_t AquantiaStatU32data[ARRAYSIZE(AquantiaStatU32Regs)];            // The place to store 32bits stat data
static uint16_t AquantiaStatLinkDropdata[ARRAYSIZE(AquantiaLinkDropRegs)];
static struct StatsCallback
{
    StatAquantiaReg     *aquantiaReg;   // information on the Aquantia reguister to read
    StatValueCallback statCallback;     // callback function after read a register
    void * context;
    uint32_t regValue;
    bool firstRegisterRead;             // to figure out if read register is LSW or MSW
    uint8_t lastDevType;                // backup last register devType to prepare skip the same register
    uint16_t lastRegiterAddr;           // backup last register addr to prepare skip the same register
    uint16_t lastValue;                 // backup last register read value
} statsCallbacks;

static struct {
    uint8_t tempThresholdWarning;       // warning level display threshold
    uint8_t tempThresholdShutdown;      // shutdown level threshold

    StatDisableCallback disableCallback;    // called after all stats are disabled

    bool hwTemperatureWarning;          // set by Aquantia HW temperature warning bit (CC00.C)
} aquantiaStatContext;

// Static Function Declarations ###################################################################
static void AquantiaStatsReadCallback(uint16_t value)           __attribute__((section(".atext")));
static void AquantiaStatsReadCallbackBitField(uint16_t value)   __attribute__((section(".atext")));
static uint32_t AquantiaReadStatRegister(
    const StatIndexOffset *pIndexOffset,
    StatsGetParam *paramInfo,
    uint32_t regValue,
    StatValueCallback statCallback,
    void *context)                                              __attribute__((section(".atext")));
static void AquantiaSaveStats(uint16_t value)                   __attribute__((section(".atext")));
static uint16_t AquantiaMonitorTemperature(uint32_t value)      __attribute__((section(".atext")));
static void MDIOD_AquantiaStopStats8Handler(void)               __attribute__((section(".atext")));
static void MDIOD_AquantiaStopStats16Handler(void)              __attribute__((section(".atext")));
// static void MDIOD_AquantiaStopStats32Handler(void)              __attribute__((section(".atext")));
static void MDIOD_AquantiaStopStatsFinished(void)               __attribute__((section(".atext")));

// Exported Function Definitions ##################################################################
void MDIOD_AquantiaStartStatsMonitor(void)                      __attribute__((section(".atext")));

// static const Definitions ##################################################################
static const StatRegistration AquantiaStat8Registration = STATMON_REGISTRATION_INIT_AQUANTIA(
        STATISTIC_DATA_SIZE_8_BITS,
        AquantiaStatU8Regs,
        AquantiaStatU8data,
        AquantiaReadStatRegister,
        STATSMON_ClearStatData,
        AQUANTIA_STATS_POLL_INTERVAL);

static const StatRegistration AquantiaStat16Registration = STATMON_REGISTRATION_INIT_AQUANTIA(
        STATISTIC_DATA_SIZE_16_BITS,
        AquantiaStatU16Regs,
        AquantiaStatU16data,
        AquantiaReadStatRegister,
        STATSMON_ClearStatData,
        AQUANTIA_STATS_POLL_INTERVAL);

static const StatRegistration AquantiaStat32Registration = STATMON_REGISTRATION_INIT_AQUANTIA(
        STATISTIC_DATA_SIZE_32_BITS,
        AquantiaStatU32Regs,
        AquantiaStatU32data,
        AquantiaReadStatRegister,
        STATSMON_ClearStatData,
        AQUANTIA_STATS_POLL_INTERVAL);

static const StatRegistration AquantiaLinkDropStatRegistration = STATMON_REGISTRATION_INIT_AQUANTIA(
        STATISTIC_DATA_SIZE_16_BITS,
        AquantiaLinkDropRegs,
        AquantiaStatLinkDropdata,
        AquantiaReadStatRegister,
        STATSMON_ClearStatData,
        AQUANTIA_STATS_POLL_INTERVAL);


//#################################################################################################
// MDIOD_AquantiaStatsInit
//  Initialize AquantiaStats Monitoring
//
// Parameters:
// Return:
// Assumptions:
//
//#################################################################################################
void MDIOD_AquantiaStatsInit(void)
{
    // Load threshold value from backup configuration
    ConfigTemperatureParams *temperatureParams =  &(Config_GetBuffer()->temperatureParams);
    if (Config_ArbitrateGetVar(CONFIG_VAR_TEMPERATURE_PARAMS, temperatureParams))
    {
        // update threshold context not to read everytime
        aquantiaStatContext.tempThresholdWarning = temperatureParams->aquantiaWarnThreshold;
        aquantiaStatContext.tempThresholdShutdown = temperatureParams->aquantiaShutThreshold;

        ilog_AQUANTIA_COMPONENT_2(ILOG_MINOR_EVENT, AQUANTIA_TEMP_THRESHOLD,
            aquantiaStatContext.tempThresholdWarning, aquantiaStatContext.tempThresholdShutdown);
    }

    STATSMON_RegisterStatgroup(&AquantiaStat8Registration);
    STATSMON_RegisterStatgroup(&AquantiaStat16Registration);
    STATSMON_RegisterStatgroup(&AquantiaStat32Registration);
    STATSMON_RegisterStatgroup(&AquantiaLinkDropStatRegistration);
}

//#################################################################################################
// MDIOD_AquantiaStartStatsMonitor
//  start Monitoring Aquantia
//
// Parameters:
// Return:
// Assumptions:
//#################################################################################################
void MDIOD_AquantiaStartStatsMonitor(void)
{
    STATSMON_StatgroupControl(&AquantiaStat8Registration, true);
    STATSMON_StatgroupControl(&AquantiaStat16Registration, true);
    STATSMON_StatgroupControl(&AquantiaStat32Registration, true);
}

//#################################################################################################
// MDIOD_AquantiaStopStatsMonitor
//  stop Monitoring Aquantia
//
// Parameters:
// Return:
// Assumptions:
//#################################################################################################
void MDIOD_AquantiaStopStatsMonitor(StatDisableCallback callback)
{
    if (callback == NULL)
    {
        // Got a stop stat request w/o call back, we should stop stat because Aquantia went to reset already
        STATSMON_StatgroupControl(&AquantiaStat8Registration, false);
        STATSMON_StatgroupControl(&AquantiaStat16Registration, false);
        STATSMON_StatgroupControl(&AquantiaStat32Registration, false);
        STATSMON_StatgroupControl(&AquantiaLinkDropStatRegistration, false);

        if(aquantiaStatContext.disableCallback)
        {
            MDIOD_AquantiaStopStatsFinished();
        }
    }
    else
    {
        if(aquantiaStatContext.disableCallback == NULL)     // Got a stop stat request and we are not processing stop stat request
        {
            aquantiaStatContext.disableCallback = callback;
            STATSMON_StatgroupDisable(&AquantiaStat8Registration, MDIOD_AquantiaStopStats8Handler);
        }
        else
        {
            ilog_AQUANTIA_COMPONENT_0(ILOG_MAJOR_EVENT, AQUANTIA_STOP_STATS_INPROGRESS);
        }
    }
}


// Component Scope Function Definitions ###########################################################
//#################################################################################################
// MDIOD_AquantiaStartLinkDropStats
//  start Monitoring Link drop test stats
//
// Parameters:
// Return:
// Assumptions:
//#################################################################################################
void MDIOD_AquantiaStartLinkDropStats(void)
{
    STATSMON_StatgroupControl(&AquantiaLinkDropStatRegistration, true);
}

//#################################################################################################
// Icmd to update Aquantia temerature warning value
//
// Parameters:
//      * val        new warning threshold temperature
// Return:
// Assumptions:
//#################################################################################################
void AQUANTIA_SetWarningTemperature(uint8_t val)
{
    ConfigTemperatureParams *temperatureParams =  &(Config_GetBuffer()->temperatureParams);

    if (Config_ArbitrateGetVar(CONFIG_VAR_TEMPERATURE_PARAMS, temperatureParams))
    {
        temperatureParams->aquantiaWarnThreshold = val;
        aquantiaStatContext.tempThresholdWarning = val;     // update warning context variable

        Config_ArbitrateSetVar(CONFIG_SRC_UART, CONFIG_VAR_TEMPERATURE_PARAMS, temperatureParams);
        ilog_AQUANTIA_COMPONENT_1(ILOG_USER_LOG, AQUANTIA_SET_TEMP_WARNING, val);
    }
}

//#################################################################################################
// Icmd to update Aquantia temerature shutdown value
//
// Parameters:
//      * val        new shutdown threshold temperature
// Return:
// Assumptions:
//#################################################################################################
void AQUANTIA_SetShutdownTemperature(uint8_t val)
{
    ConfigTemperatureParams *temperatureParams = &(Config_GetBuffer()->temperatureParams);

    if (Config_ArbitrateGetVar(CONFIG_VAR_TEMPERATURE_PARAMS, temperatureParams))
    {
        temperatureParams->aquantiaShutThreshold = val;
        aquantiaStatContext.tempThresholdShutdown = val;    // update shutdown context variable

        Config_ArbitrateSetVar(CONFIG_SRC_UART, CONFIG_VAR_TEMPERATURE_PARAMS, temperatureParams);
        ilog_AQUANTIA_COMPONENT_1(ILOG_USER_LOG, AQUANTIA_SET_TEMP_SHUTDOWN, val);
    }
}

//#################################################################################################
// AquantiaInNomalOperation
//  Check Aquantia status when we meet temperature failure case
//  Some EMI testing can cause Aquantia into reset and stat can read wrong indication
//
// Parameters:
// Return: True (Aquantia is on normal operation), False (Aquantia is under wrong state)
// Assumptions:
//
//#################################################################################################
bool AquantiaInNomalOperation(void)
{
    bool normalOperation = true;
    uint16_t threshold = MdioIndirectReadSync(AQUANTIA_PHY_ADDR, MDIO_DEVTYPE_GLOBAL, GLOBAL_THRML_PROV2_OFFSET, MDIO_MASTER_MOTHERBOARD);

    if(threshold != GLOBAL_THRML_PROV2_HIGH_TEMP_THRESH)
    {
        normalOperation = false;
    }

    ilog_AQUANTIA_COMPONENT_2(ILOG_MAJOR_EVENT, AQUANTIA_NORMAL_OPERATION, threshold, normalOperation);
    return normalOperation;
}

// Static Function Definitions ####################################################################
//#################################################################################################
// Get Data for Aquantia bit field stats monitor
//
// Parameters:
// Return:
// Assumptions: Only the case of bit read in the same register, it tries to read the same register many time
//              bitMask & offSet works with not regAddress2 but regAddress1
//#################################################################################################
static uint32_t AquantiaReadStatRegister(
    const StatIndexOffset *pIndexOffset,
    StatsGetParam *paramInfo,
    uint32_t regValue,
    StatValueCallback statCallback,
    void *context)
{
    // store args for callback to use
    statsCallbacks.aquantiaReg = &(paramInfo->AquantiaRegRead);
    statsCallbacks.statCallback = statCallback;
    statsCallbacks.context = context;
    statsCallbacks.regValue = regValue;
    statsCallbacks.firstRegisterRead = true;       // Initialize to indicate reading first register

    // Check the same register which can be cleared by read
    // If the register is same, don't read it again and use last read value
    if(    (statsCallbacks.lastDevType == paramInfo->AquantiaRegRead.devType)
        && (statsCallbacks.lastRegiterAddr == paramInfo->AquantiaRegRead.regAddress1) )
    {
        AquantiaStatsReadCallbackBitField(statsCallbacks.lastValue);
    }
    else
    {
        // read address1 if address2(LSW) doesn't exist, read address2 first if address2 exists
        bool address1 = (paramInfo->AquantiaRegRead.regAddress2 == AQUANTIA_NULL_ADDR);
        uint16_t readAddress = address1 ? paramInfo->AquantiaRegRead.regAddress1 : paramInfo->AquantiaRegRead.regAddress2;

        // use bitField callback if address1 read and bitMask is not 0
        bool bitCallback = (address1 && (paramInfo->AquantiaRegRead.bitMask != AQUANTIA_NO_MASK));

        // chose Motherboard and phy addr for mux port except devicetype = 0x05 (MDIO_DEVTYPE_DTE_XS)
        uint8_t device = AQUANTIA_PHY_ADDR;
        uint8_t muxPort = MDIO_MASTER_MOTHERBOARD;
        if(paramInfo->AquantiaRegRead.devType == MDIO_DEVTYPE_DTE_XS)
        {
            device = CORE_PHY_ADDR;
            muxPort = MDIO_SLAVE_RXAUI_CORE;
        }

        MdioIndirectReadASync(
            device,
            paramInfo->AquantiaRegRead.devType,
            readAddress,
            bitCallback ? AquantiaStatsReadCallbackBitField : AquantiaStatsReadCallback,
            muxPort);

        // backup last register address1 to prepare skip the same register
        statsCallbacks.lastDevType     = paramInfo->AquantiaRegRead.devType;
        statsCallbacks.lastRegiterAddr = paramInfo->AquantiaRegRead.regAddress1;
    }

    return(0);  // no value available at this time
}

//#################################################################################################
// AquantiaStatsReadCallbackBitField
//  Process bit & backup entire register value
//
// Parameters:
// Return:
// Assumptions: To use lastValue corretly,
//              need to access the same register consecutively w/o intervene by another register
//
//#################################################################################################
static void AquantiaStatsReadCallbackBitField(uint16_t value)
{
    uint16_t bitMask = statsCallbacks.aquantiaReg->bitMask;
    uint8_t bitOffset = statsCallbacks.aquantiaReg->bitOffset;
    uint16_t returnValue = ( value & bitMask ) >> bitOffset;

    // backup last value to prepare skip reading the same register
    // this is because reading a register clears the register value
    statsCallbacks.lastValue = value;

    AquantiaStatsReadCallback(returnValue);
}

//#################################################################################################
// AquantiaStatsReadCallback
//  Process data & Send Data to stats monitor.
//
// Parameters:
// Return:
// Assumptions: Some of Aquantia value can get by reading LSW & MSW registers (read twice)
//              In this case, must read LSW first and MSW next. Also, MSW has bitMask & offset Value
//#################################################################################################
static void AquantiaStatsReadCallback(uint16_t value)
{
    StatAquantiaReg     *aquantiaReg = statsCallbacks.aquantiaReg;

    if(aquantiaReg->regAddress2 != AQUANTIA_NULL_ADDR)
    {
        // The stat need to read two registers
        if(statsCallbacks.firstRegisterRead)
        {
            // it read 1st(LSW) register and need to read second register
            statsCallbacks.firstRegisterRead = false;

            // need to read two registers, but update LSW value first
            AquantiaSaveStats(value);

            MdioIndirectReadASync(                      // read MSW register next
                AQUANTIA_PHY_ADDR,
                aquantiaReg->devType,
                aquantiaReg->regAddress1,
                AquantiaStatsReadCallbackBitField,      // All MSW has bitMask & offset Value
                MDIO_MASTER_MOTHERBOARD);

            return;                                     // Don't call statCallback until read LSW
        }
        else
        {
            // it read 2nd(MSW) register & update
            statsCallbacks.regValue += (value << 16);   // update MSW value
        }
    }
    else
    {
        // Check temperature case
        if (   (aquantiaReg->regAddress1 == GLOBAL_THERMAL_STATUS_1_ADDR)
            && (aquantiaReg->devType == MDIO_DEVTYPE_GLOBAL) )
        {
            value = AquantiaMonitorTemperature(value);
        }
        else if (   (aquantiaReg->regAddress1 == GLOBAL_ALARMS_1_ADDR)
                 && (aquantiaReg->devType == MDIO_DEVTYPE_GLOBAL) )
        {
            // Check Aquantia HW temperature threshold over
            // Don't merge below if case with above, some address has NULL bitMask and it will cause Trap Error
            if ( (aquantiaReg->bitMask == GLOBAL_HIGH_TEMP_FAIL_MASK)
                && (value == 1) )
            {
                if(AquantiaInNomalOperation())
                {
                    MDIOD_aquantiaReadJunctionTemp();               // Print out current temperature
                    AquantiaMonitorTemperature(aquantiaStatContext.tempThresholdShutdown * 256);
                }
            }
            else if(aquantiaReg->bitMask == GLOBAL_HIGH_TEMP_WARNING_MASK)
            {
                if(value == 1)
                {
                    aquantiaStatContext.hwTemperatureWarning = true;
                    AquantiaMonitorTemperature(aquantiaStatContext.tempThresholdWarning * 256);
                }
                else
                {
                    aquantiaStatContext.hwTemperatureWarning = false;
                }
            }
        }

        AquantiaSaveStats(value);
    }

    // return value to stat monitor
    statsCallbacks.statCallback(
        statsCallbacks.context,
        statsCallbacks.regValue);
}

//#################################################################################################
// AquantiaMonitorTemperature
//  Handling temperature read value
//
// Parameters:
// Return:
// Assumptions:
//#################################################################################################
static uint16_t AquantiaMonitorTemperature(uint32_t value)
{
    uint16_t temperature = value / 256;

    if(temperature >= aquantiaStatContext.tempThresholdShutdown)
    {
        if(AquantiaInNomalOperation())
        {
            ILOG_istatus(ISTATUS_AQUANTIA_TEMP_FAULT, 1, temperature);

            LED_SetLedState(LS_TEMP_FAULT, true);       // set LED fault
            killSystem();
        }
    }
    else if ((temperature >= aquantiaStatContext.tempThresholdWarning) || aquantiaStatContext.hwTemperatureWarning)
    {
        LED_SetLedState(LS_TEMP_WARN_AQUANTIA, true);       // set LED warning
    }
    else
    {
        temperature = statsCallbacks.regValue;              // For below Threshold, keeps old value not to show log
        LED_SetLedState(LS_TEMP_WARN_AQUANTIA, false);      // clear LED warning
    }

    return temperature;
}

//#################################################################################################
// AquantiaSaveStats
//  Save stat data depends on option flag
//
// Parameters:
// Return:
// Assumptions: It stores LSW value or single register value into regValue storing stat mon data
//              MSW value will be stored separtely
//#################################################################################################
static void AquantiaSaveStats(uint16_t value)
{
    // STATMON_PARAM_FLAG_RELATIVE_VALUE :1, keep adding value and display if the value changes
    // STATMON_PARAM_FLAG_RELATIVE_VALUE :0, update value and display if the value changes
    if(statsCallbacks.aquantiaReg->commonParam.flags & STATMON_PARAM_FLAG_RELATIVE_VALUE)
    {
        statsCallbacks.regValue += value;
    }
    else
    {
        statsCallbacks.regValue = value;
    }
}


//#################################################################################################
// MDIOD_AquantiaStopStats8Handler
//
// Parameters:
// Return:
// Assumptions:
//#################################################################################################
static void MDIOD_AquantiaStopStats8Handler(void)
{
    STATSMON_StatgroupDisable(&AquantiaStat16Registration, MDIOD_AquantiaStopStats16Handler);
}

//#################################################################################################
// MDIOD_AquantiaStopStats16Handler
//
// Parameters:
// Return:
// Assumptions:
//#################################################################################################
static void MDIOD_AquantiaStopStats16Handler(void)
{
    STATSMON_StatgroupDisable(&AquantiaStat32Registration, MDIOD_AquantiaStopStatsFinished);
    // STATSMON_StatgroupDisable(&AquantiaStat32Registration, MDIOD_AquantiaStopStats32Handler);
}

//#################################################################################################
// MDIOD_AquantiaStopStats32Handler
//
// Parameters:
// Return:
// Assumptions:
//#################################################################################################
// static void MDIOD_AquantiaStopStats32Handler(void)
// {
//     UART_printf("ALAN Aquantia: %d\n",__LINE__);
//     STATSMON_StatgroupDisable(&AquantiaLinkDropStatRegistration, aquantiaStatContext.disableCallback);
// }

//#################################################################################################
// Called when we are done checking the stats, and they are shut down
//
// Parameters:
// Return:
// Assumptions:
//#################################################################################################
static void MDIOD_AquantiaStopStatsFinished(void)
{
    iassert_AQUANTIA_COMPONENT_0(aquantiaStatContext.disableCallback != NULL, AQUANTIA_STOP_STAT_NULL_POINTER);

    StatDisableCallback disableCallback = aquantiaStatContext.disableCallback;
    aquantiaStatContext.disableCallback = NULL; // in case stop stats is called, we are done
    aquantiaStatContext.hwTemperatureWarning = false;
    disableCallback();
}

